In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df = pd.read_csv('cleaned_subway/raw_subway_2019-11-28_AM.csv')

In [3]:
df['request_date'] = pd.to_datetime(df['request_date'])

In [4]:
df = df.sort_values(by = 'timint')

In [5]:
df['platformid'] = df['station_char'].str[3]

In [6]:
df

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid
96041,2305871,34246572163,YIE1,SHEP,0.000000,East,463,AtStation,64,4,2019-11-28 08:25:51,32685,2019-11-28 08:25:51.333503-05:00,2019-11-28,8,3,AM,1
70449,2284190,34250776188,DNW1,BD,0.000000,East,238,AtStation,41,2,2019-11-28 11:47:46,32390,2019-11-28 11:47:43.252615-05:00,2019-11-28,11,3,AM,1
108705,2317542,34249245226,DAV1,YUS,0.000000,North,23,AtStation,26,1,2019-11-28 10:33:44,32845,2019-11-28 10:33:43.807289-05:00,2019-11-28,10,3,AM,1
130034,2331258,34250039928,STP1,YUS,0.000000,North,142,AtStation,13,1,2019-11-28 11:11:43,33032,2019-11-28 11:11:43.844225-05:00,2019-11-28,11,3,AM,1
20763,2253499,34248521900,YNG2,BD,0.000000,West,209,AtStation,22,1,2019-11-28 09:58:44,31970,2019-11-28 09:58:43.613983-05:00,2019-11-28,9,3,AM,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131973,2332904,34246290251,PVL2,YUS,23.830480,South,101,Arriving,78,1,2019-11-28 08:11:46,33054,2019-11-28 08:11:43.647875-05:00,2019-11-28,8,3,AM,2
43569,2267264,34246374797,YUN2,YUS,24.054304,South,102,Arriving,77,1,2019-11-28 08:15:46,32158,2019-11-28 08:15:43.330515-05:00,2019-11-28,8,3,AM,2
80650,2293189,34246332696,HWY2,YUS,24.077273,South,101,Arriving,79,1,2019-11-28 08:13:46,32513,2019-11-28 08:13:43.803495-05:00,2019-11-28,8,3,AM,2
27515,2257777,34246271179,PVL2,YUS,25.284794,South,101,Arriving,78,1,2019-11-28 08:10:55,32029,2019-11-28 08:10:51.335830-05:00,2019-11-28,8,3,AM,2
26169,2257206,34246227351,YUN2,YUS,26.226955,South,101,Arriving,77,1,2019-11-28 08:08:43,32021,2019-11-28 08:08:43.525283-05:00,2019-11-28,8,3,AM,2

# Filtering for only the most recent data in a request

Since each request has multiple train arrival times.

We're filtering on `station_char` and `requestid`. This might cause an issue with terminus, but we'll deal with it later.

In [7]:
df_newest = df.drop_duplicates(subset = ['requestid', 'station_char'])

In [8]:
df_newest[df_newest['station_char'] == 'KIP1'].sort_values(by = 'request_date').head(30)

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid
48032,2269017,34244782417,KIP1,BD,0.604911,West,213,Arriving,33,2,2019-11-28 07:00:47,32182,2019-11-28 07:00:43.976162-05:00,2019-11-28,7,3,AM,1
60102,2278021,34244803350,KIP1,BD,0.000000,East,213,AtStation,33,2,2019-11-28 07:01:44,32306,2019-11-28 07:01:43.534795-05:00,2019-11-28,7,3,AM,1
16818,2249606,34244827162,KIP1,BD,0.000000,East,213,AtStation,33,2,2019-11-28 07:02:47,31917,2019-11-28 07:02:43.576920-05:00,2019-11-28,7,3,AM,1
120372,2325106,34244846809,KIP1,BD,1.273126,West,215,Arriving,33,2,2019-11-28 07:03:46,32948,2019-11-28 07:03:43.456933-05:00,2019-11-28,7,3,AM,1
117256,2322606,34244867650,KIP1,BD,0.512303,East,215,Arriving,33,2,2019-11-28 07:04:46,32914,2019-11-28 07:04:43.696777-05:00,2019-11-28,7,3,AM,1
99405,2308182,34244889783,KIP1,BD,0.000000,East,215,AtStation,33,2,2019-11-28 07:05:44,32717,2019-11-28 07:05:43.659269-05:00,2019-11-28,7,3,AM,1
34657,2261607,34244912528,KIP1,BD,0.000000,East,215,AtStation,33,2,2019-11-28 07:06:45,32081,2019-11-28 07:06:43.531235-05:00,2019-11-28,7,3,AM,1
45810,2268129,34244932324,KIP1,BD,0.000000,East,215,AtStation,33,2,2019-11-28 07:07:42,32170,2019-11-28 07:07:43.660882-05:00,2019-11-28,7,3,AM,1
101625,2311184,34244953520,KIP1,BD,0.440788,West,217,Arriving,33,2,2019-11-28 07:08:46,32758,2019-11-28 07:08:43.561103-05:00,2019-11-28,7,3,AM,1
72189,2286092,34244977459,KIP1,BD,0.000000,East,217,AtStation,33,2,2019-11-28 07:09:54,32416,2019-11-28 07:09:51.436780-05:00,2019-11-28,7,3,AM,1
82447,2295327,34244994204,KIP1,BD,0.000000,East,217,AtStation,33,2,2019-11-28 07:10:42,32542,2019-11-28 07:10:43.603287-05:00,2019-11-28,7,3,AM,1
23946,2256545,34245017957,KIP1,BD,0.000000,East,217,AtStation,33,2,2019-11-28 07:11:47,32012,2019-11-28 07:11:43.518989-05:00,2019-11-28,7,3,AM,1
132883,2333351,34245040143,KIP1,BD,0.604911,West,219,Arriving,33,2,2019-11-28 07:12:47,33060,2019-11-28 07:12:43.503487-05:00,2019-11-28,7,3,AM,1
52951,2273419,34245060712,KIP1,BD,0.000000,East,219,AtStation,33,2,2019-11-28 07:13:46,32243,2019-11-28 07:13:43.682453-05:00,2019-11-28,7,3,AM,1
59656,2277606,34245081470,KIP1,BD,0.000000,East,219,AtStation,33,2,2019-11-28 07:14:48,32300,2019-11-28 07:14:43.678859-05:00,2019-11-28,7,3,AM,1
7877,2242570,34245103985,KIP1,BD,1.273126,West,221,Arriving,33,2,2019-11-28 07:15:47,31821,2019-11-28 07:15:43.578453-05:00,2019-11-28,7,3,AM,1
95392,2305692,34245124949,KIP1,BD,0.256149,East,221,Arriving,33,2,2019-11-28 07:16:43,32683,2019-11-28 07:16:43.596174-05:00,2019-11-28,7,3,AM,1
132435,2332981,34245148492,KIP1,BD,0.000000,East,221,AtStation,33,2,2019-11-28 07:17:46,33055,2019-11-28 07:17:43.408500-05:00,2019-11-28,7,3,AM,1
53840,2274355,34245171510,KIP1,BD,0.000000,East,221,AtStation,33,2,2019-11-28 07:18:53,32256,2019-11-28 07:18:51.440586-05:00,2019-11-28,7,3,AM,1
74866,2287408,34245192271,KIP1,BD,0.000000,East,221,AtStation,33,2,2019-11-28 07:19:59,32434,2019-11-28 07:19:59.426707-05:00,2019-11-28,7,3,AM,1
44924,2267760,34245212626,KIP1,BD,2.823427,West,226,Arriving,33,2,2019-11-28 07:20:54,32165,2019-11-28 07:20:51.445349-05:00,2019-11-28,7,3,AM,1
48481,2269461,34245231597,KIP1,BD,2.422204,West,226,Arriving,33,2,2019-11-28 07:21:46,32188,2019-11-28 07:21:43.449989-05:00,2019-11-28,7,3,AM,1
117703,2323263,34245252184,KIP1,BD,1.273126,West,25,Arriving,33,2,2019-11-28 07:22:42,32923,2019-11-28 07:22:43.489851-05:00,2019-11-28,7,3,AM,1
93160,2303952,34245274963,KIP1,BD,0.000000,East,25,AtStation,33,2,2019-11-28 07:23:47,32659,2019-11-28 07:23:44.111042-05:00,2019-11-28,7,3,AM,1
73966,2286743,34245296163,KIP1,BD,1.273126,West,224,Arriving,33,2,2019-11-28 07:24:52,32425,2019-11-28 07:24:51.444872-05:00,2019-11-28,7,3,AM,1
111014,2318801,34245317689,KIP1,BD,0.604911,West,224,Arriving,33,2,2019-11-28 07:25:48,32862,2019-11-28 07:25:43.835381-05:00,2019-11-28,7,3,AM,1
52504,2272904,34245337827,KIP1,BD,1.273126,West,227,Arriving,33,2,2019-11-28 07:26:47,32236,2019-11-28 07:26:43.775705-05:00,2019-11-28,7,3,AM,1
102959,2313006,34245361626,KIP1,BD,0.000000,East,227,AtStation,33,2,2019-11-28 07:27:53,32783,2019-11-28 07:27:50.446513-05:00,2019-11-28,7,3,AM,1
1138,2238290,34245379905,KIP1,BD,0.000000,East,227,AtStation,33,2,2019-11-28 07:28:46,31763,2019-11-28 07:28:43.575102-05:00,2019-11-28,7,3,AM,1
40460,2264987,34245402713,KIP1,BD,0.000000,East,227,AtStation,33,2,2019-11-28 07:29:54,32127,2019-11-28 07:29:51.452551-05:00,2019-11-28,7,3,AM,1

In [9]:
df_newest[['trainid']].drop_duplicates()

        trainid
96041       463
70449       238
108705       23
130034      142
20763       209
...         ...
115229       28
117710       22
8810        762
121716       39
14671       563

[173 rows x 1 columns]

In [10]:
single_train = df_newest[df_newest['trainid'] == 226]

In [11]:
single_train['estimated_arrival'] = single_train['request_date'] + pd.to_timedelta(single_train['timint'], 'm')

/var/folders/zw/x46df3ms6r5391lyb_y98z600000gn/T/ipykernel_9069/1386873350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  single_train['estimated_arrival'] = single_train['request_date'] + pd.to_timedelta(single_train['timint'], 'm')

In [12]:
single_train = single_train.sort_values(by = 'request_date')
single_train.tail(20)

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid,estimated_arrival
121326,2325852,34247165211,OSS2,BD,0.000000,West,226,AtStation,44,2,2019-11-28 08:53:48,32958,2019-11-28 08:53:43.497494-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:53:43.497494-05:00
56582,2275990,34247184335,DUF2,BD,0.613117,West,226,Arriving,43,2,2019-11-28 08:54:47,32278,2019-11-28 08:54:43.395780-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:55:20.182795380-05:00
115537,2321001,34247206873,LAN2,BD,0.590843,West,226,Arriving,42,2,2019-11-28 08:55:48,32892,2019-11-28 08:55:43.358260-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:56:18.808844620-05:00
72679,2286247,34247228881,DNW2,BD,1.423205,West,226,Arriving,41,2,2019-11-28 08:56:46,32418,2019-11-28 08:56:43.960035-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:58:09.352311900-05:00
72685,2286248,34247228878,LAN2,BD,0.000000,West,226,AtStation,42,2,2019-11-28 08:56:46,32418,2019-11-28 08:56:43.960439-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:56:43.960439-05:00
42299,2266469,34247253704,DNW2,BD,0.000000,West,226,AtStation,41,2,2019-11-28 08:57:54,32147,2019-11-28 08:57:51.354921-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:57:51.354921-05:00
42293,2266468,34247253819,KEL2,BD,1.166909,West,226,Arriving,40,2,2019-11-28 08:57:55,32147,2019-11-28 08:57:51.355291-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:59:01.369821760-05:00
2072,2239185,34247271873,KEL2,BD,0.232557,West,226,Arriving,40,2,2019-11-28 08:58:47,31775,2019-11-28 08:58:43.599151-05:00,2019-11-28,8,3,AM,2,2019-11-28 08:58:57.552543280-05:00
88292,2300719,34247293418,HPK2,BD,0.363415,West,226,Arriving,39,2,2019-11-28 08:59:56,32615,2019-11-28 08:59:51.358700-05:00,2019-11-28,8,3,AM,2,2019-11-28 09:00:13.163623100-05:00
54321,2274508,34247312700,RUN2,BD,0.999392,West,226,Arriving,38,2,2019-11-28 09:00:46,32258,2019-11-28 09:00:43.592771-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:01:43.556309480-05:00
11020,2245455,34247336450,JNE2,BD,1.264891,West,226,Arriving,37,2,2019-11-28 09:01:48,31860,2019-11-28 09:01:43.789306-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:02:59.682751720-05:00
11026,2245456,34247336447,RUN2,BD,0.000000,West,226,AtStation,38,2,2019-11-28 09:01:48,31860,2019-11-28 09:01:43.789699-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:01:43.789699-05:00
5197,2241028,34247360269,JNE2,BD,0.000000,West,226,AtStation,37,2,2019-11-28 09:02:59,31800,2019-11-28 09:02:59.346567-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:02:59.346567-05:00
86498,2299312,34247374342,OML2,BD,0.710670,West,226,Arriving,36,2,2019-11-28 09:03:46,32596,2019-11-28 09:03:43.847646-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:04:26.487875340-05:00
107449,2317052,34247418012,RYK2,BD,0.736846,West,226,Arriving,35,2,2019-11-28 09:05:46,32838,2019-11-28 09:05:43.644890-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:06:27.855623660-05:00
10561,2245009,34247439317,RYK2,BD,0.000000,West,226,AtStation,35,2,2019-11-28 09:06:46,31854,2019-11-28 09:06:43.289701-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:06:43.289701-05:00
109676,2317778,34247482335,ISL2,BD,0.613869,West,226,Arriving,34,2,2019-11-28 09:08:45,32848,2019-11-28 09:08:43.344431-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:09:20.176582160-05:00
47596,2268722,34247502716,ISL2,BD,0.257104,West,226,Arriving,34,2,2019-11-28 09:09:53,32178,2019-11-28 09:09:50.362133-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:10:05.788388660-05:00
77530,2290328,34247522235,ISL2,BD,0.000000,West,226,AtStation,34,2,2019-11-28 09:10:45,32474,2019-11-28 09:10:43.531833-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:10:43.531833-05:00
91822,2303731,34247605041,KIP2,BD,0.447967,West,226,Arriving,33,2,2019-11-28 09:14:47,32656,2019-11-28 09:14:43.558249-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:15:10.436247700-05:00

## Creating Trip Ids for Each Train

Terminus are not represented in each trip (ie, its not guaranteed Kipling will show up in the trip)

Trip Ids are only used for the purpose of cleaning up the data, not for any analysis/graph building.

In [13]:
single_train['trip'] = (single_train['traindirection'] != single_train['traindirection'].shift(1)).cumsum() - 1

In [14]:
single_train.groupby('trip').count()

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid,estimated_arrival
trip,,,,,,,,,,,,,,,,,,,
0,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81
1,169,169,169,169,169,169,169,169,169,169,169,169,169,169,169,169,169,169,169
2,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61

In [15]:
trip_num = single_train['trip'].max()

## Setting Arrival Times

Must select latest possible request that the train isn't arrived at the station, for a "best guess" of when a train arrives at a station. If a station doesn't have that time, then we need to take the earliest time a station is waiting at a station.

If earlier requests show an earlier arrival time, ignore as that means the train was delayed, and the latest request will show an updated/delayed arrival time.

API runs once per minute, so the error is limited to minute resolution

In [16]:
def process_trip(single_trip):

    arrivals = single_trip[['station_char']].drop_duplicates()
    arrival_max = single_trip[single_trip['timint']!=0]
    arrival_max = arrival_max.sort_values(by = 'request_date', ascending = False)
    arrival_max = arrival_max.drop_duplicates(subset = ['station_char'])[['station_char', 'estimated_arrival']]

    arrivals_at_station = single_trip[single_trip['timint']==0]
    arrivals_at_station = arrivals_at_station.sort_values(by = 'estimated_arrival')
    arrivals_at_station  = arrivals_at_station.drop_duplicates(subset = ['station_char'])[['station_char',
                                                                                           'estimated_arrival']]
    arrivals = arrivals.merge(arrival_max, how = 'left')

    arrivals_at_station = arrivals_at_station.rename(columns = {'estimated_arrival':'at_station_time'})
    arrivals = arrivals.merge(arrivals_at_station, how = 'left')
    arrivals['arrival'] = True

    arrivals['estimated_arrival'] = np.where(arrivals['estimated_arrival'].isna(), 
                                             arrivals['at_station_time'], arrivals['estimated_arrival'])

    arrivals['estimated_arrival'] = np.where(arrivals['estimated_arrival']>arrivals['at_station_time'], 
                                             arrivals['at_station_time'], arrivals['estimated_arrival'])

    arrivals = arrivals.sort_values(by = 'estimated_arrival').reset_index(drop = True)
    
    departures = single_trip[['station_char']].drop_duplicates()
    departures_max = single_trip[single_trip['timint'] == 0]
    departures_max = departures_max.sort_values(by = 'estimated_arrival', ascending = False)
    departures_max = departures_max.drop_duplicates(subset = ['station_char'])[['station_char', 'estimated_arrival']]

    departures = departures.merge(departures_max, how = 'left')
    departures['departure'] = True

    departures = departures.merge(arrivals.rename(columns = {'estimated_arrival':'before_station_time'}))

    departures['estimated_arrival'] = np.where(departures['estimated_arrival'].isna(), departures['before_station_time'], departures['estimated_arrival'])
    departures = departures[['station_char', 'estimated_arrival', 'departure']]
    departures = departures.sort_values(by = 'estimated_arrival').reset_index(drop = True)
    arrivals['previous_depart'] = departures['estimated_arrival'].shift(1)


    arrivals['estimated_arrival'] = np.where(arrivals['estimated_arrival'] < arrivals['previous_depart'], 
                                         arrivals['at_station_time'], arrivals['estimated_arrival'])
    
    arrivals = arrivals[['station_char', 'estimated_arrival', 'arrival']]
    
    single_trip = single_trip.merge(arrivals, how = 'left')
    single_trip = single_trip.merge(departures, how = 'left')

    single_trip = single_trip.sort_values(by = 'estimated_arrival')
    
    single_trip = single_trip[['station_char', 'subwayline', 'timint', 'traindirection', 'trip','trainid',
                 'stationid', 'estimated_arrival', 'arrival', 'departure']]
    
    return single_trip[~single_trip['departure'].isna()].reset_index(drop = True), single_trip[~single_trip['arrival'].isna()].reset_index(drop = True)

In [17]:
arrival_list = []
departure_list = []
for i in range(trip_num + 1):
    if i == 0:
        current_departures, current_arrivals = process_trip(single_train[single_train['trip'] == i])
    
    if i < trip_num:
        next_departures, next_arrivals = process_trip(single_train[single_train['trip'] == i + 1])

    arrival_limit = next_arrivals.head(1)[['estimated_arrival']].iloc[0,0] - datetime.timedelta(seconds = 45)
    
    if len(current_arrivals['station_char']) == 1:
        pass

    elif i < trip_num:
    
        current_departures = current_departures[current_departures['estimated_arrival'] < arrival_limit]
        current_arrivals = current_arrivals[current_arrivals['estimated_arrival'] < arrival_limit]
    else:
        pass

    arrival_list.append(current_arrivals.copy())
    departure_list.append(current_departures.copy())

    current_arrivals = next_arrivals
    current_departures = next_departures

In [18]:
arrival_trip = pd.concat(arrival_list)
departure_trip = pd.concat(departure_list)

In [19]:
if arrival_trip['estimated_arrival'].max().hour < 11:
    if arrival_trip['subwayline'].drop_duplicates().iloc[0] == 'BD':
        cutoff = arrival_trip[arrival_trip['stationid'] == 55]['estimated_arrival'].max()
        
    elif (arrival_trip['subwayline'].drop_duplicates().iloc[0] == 'YUS') & (arrival_trip.tail(1)['stationid'].iloc[0] == 80):
        cutoff = arrival_trip[arrival_trip['stationid'] == 80]['estimated_arrival'].max()
    
    elif arrival_trip['subwayline'].drop_duplicates().iloc[0] == 'YUS':
        cutoff = arrival_trip[arrival_trip['stationid'] == 1]['estimated_arrival'].max()
    else:
        cutoff = arrival_trip['estimated_arrival'].max()

In [20]:
arrival_trip = arrival_trip[arrival_trip['estimated_arrival'] <= cutoff]
departure_trip = departure_trip[departure_trip['estimated_arrival'] <= cutoff]

In [21]:
arrival_trip = arrival_trip.reset_index(drop = True).reset_index()

In [22]:
departure_trip = departure_trip.reset_index(drop = True).reset_index()
departure_trip['index'] = departure_trip['index'] + 1

In [23]:
departure_trip = departure_trip.rename(columns = {'station_char':'dep_stn_char', 'estimated_arrival':'dep_time'})
arrival_trip = arrival_trip.rename(columns = {'station_char':'arr_stn_char', 'estimated_arrival':'arr_time'})

In [24]:
arrival_trip

,index,arr_stn_char,subwayline,timint,traindirection,trip,trainid,stationid,arr_time,arrival,departure
0,0,SGL2,BD,0.294249,West,0,226,48,2019-11-28 07:01:09.075722860-05:00,True,NaN
1,1,BSP2,BD,0.570181,West,0,226,47,2019-11-28 07:02:17.764470240-05:00,True,NaN
2,2,BAT2,BD,0.699868,West,0,226,46,2019-11-28 07:03:25.581713520-05:00,True,NaN
3,3,CHR2,BD,0.993554,West,0,226,45,2019-11-28 07:04:43.084502760-05:00,True,NaN
4,4,OSS2,BD,0.376657,West,0,226,44,2019-11-28 07:06:06.270735-05:00,True,True
5,5,DUF2,BD,0.000000,West,0,226,43,2019-11-28 07:07:43.672878-05:00,True,True
6,6,LAN2,BD,0.845843,West,0,226,42,2019-11-28 07:08:34.422911620-05:00,True,NaN
7,7,DNW2,BD,0.000000,West,0,226,41,2019-11-28 07:09:51.429448-05:00,True,True
8,8,KEL2,BD,0.596558,West,0,226,40,2019-11-28 07:11:27.229526620-05:00,True,NaN
9,9,HPK2,BD,0.000000,West,0,226,39,2019-11-28 07:12:43.505560-05:00,True,True
10,10,RUN2,BD,0.000000,West,0,226,38,2019-11-28 07:13:43.684322-05:00,True,True
11,11,JNE2,BD,0.647876,West,0,226,37,2019-11-28 07:15:22.554060760-05:00,True,True
12,12,OML2,BD,0.000000,West,0,226,36,2019-11-28 07:16:43.597419-05:00,True,NaN
13,13,RYK2,BD,0.000000,West,0,226,35,2019-11-28 07:18:51.439817-05:00,True,NaN
14,14,ISL2,BD,0.000000,West,0,226,34,2019-11-28 07:21:43.450338-05:00,True,NaN
15,15,KIP2,BD,0.256149,East,1,226,33,2019-11-28 07:33:59.230275859-05:00,True,True
16,16,KIP1,BD,0.256149,East,1,226,33,2019-11-28 07:33:59.230275859-05:00,True,NaN
17,17,ISL1,BD,0.483770,East,1,226,34,2019-11-28 07:39:12.566609240-05:00,True,True
18,18,RYK1,BD,0.645449,East,1,226,35,2019-11-28 07:41:22.271913140-05:00,True,True
19,19,OML1,BD,1.090832,East,1,226,36,2019-11-28 07:43:48.950452480-05:00,True,True
20,20,JNE1,BD,0.000000,East,1,226,37,2019-11-28 07:44:50.460964-05:00,True,True
21,21,RUN1,BD,0.328246,East,1,226,38,2019-11-28 07:46:03.354929240-05:00,True,NaN
22,22,HPK1,BD,0.000000,East,1,226,39,2019-11-28 07:47:43.892868-05:00,True,True
23,23,KEL1,BD,0.000000,East,1,226,40,2019-11-28 07:48:43.442220-05:00,True,True
24,24,DNW1,BD,0.583663,East,1,226,41,2019-11-28 07:50:18.974181520-05:00,True,NaN
25,25,LAN1,BD,0.000000,East,1,226,42,2019-11-28 07:51:43.497170-05:00,True,True
26,26,DUF1,BD,0.243254,East,1,226,43,2019-11-28 07:52:58.063850760-05:00,True,NaN
27,27,OSS1,BD,0.000000,East,1,226,44,2019-11-28 07:54:43.531960-05:00,True,True
28,28,CHR1,BD,0.731520,East,1,226,45,2019-11-28 07:56:27.460560-05:00,True,NaN
29,29,BAT1,BD,0.293077,East,1,226,46,2019-11-28 07:58:01.194801380-05:00,True,True
30,30,BSP1,BD,0.703092,East,1,226,47,2019-11-28 07:59:25.738037280-05:00,True,NaN
31,31,SGL1,BD,0.933766,East,1,226,48,2019-11-28 08:00:39.436358240-05:00,True,NaN
32,32,BAU1,BD,0.598023,East,1,226,49,2019-11-28 08:02:19.617056720-05:00,True,NaN
33,33,YNG1,BD,0.819466,East,1,226,50,2019-11-28 08:03:40.491852240-05:00,True,NaN
34,34,SHE1,BD,0.668215,East,1,226,51,2019-11-28 08:05:30.417116100-05:00,True,NaN
35,35,CFK1,BD,1.065651,East,1,226,52,2019-11-28 08:06:55.263399140-05:00,True,True
36,36,BRD1,BD,0.000000,East,1,226,53,2019-11-28 08:08:51.326027-05:00,True,True
37,37,CHE1,BD,0.000000,East,1,226,54,2019-11-28 08:10:51.326328-05:00,True,True
38,38,PAP1,BD,0.994287,East,1,226,55,2019-11-28 08:11:50.983914280-05:00,True,NaN
39,39,DON1,BD,0.962781,East,1,226,56,2019-11-28 08:12:49.087334140-05:00,True,NaN
40,40,GWD1,BD,0.000000,East,1,226,57,2019-11-28 08:13:51.320546-05:00,True,True
41,41,COX1,BD,0.316523,East,1,226,58,2019-11-28 08:15:10.318919620-05:00,True,True
42,42,WDB1,BD,0.000000,East,1,226,59,2019-11-28 08:16:51.327709-05:00,True,True
43,43,MST1,BD,0.859302,East,1,226,60,2019-11-28 08:18:42.885787280-05:00,True,True
44,44,VPK1,BD,0.000000,East,1,226,61,2019-11-28 08:19:51.327655-05:00,True,True
45,45,KEN2,BD,0.000000,West,2,226,63,2019-11-28 08:21:51.328501-05:00,True,NaN
46,46,WAR2,BD,0.578534,West,2,226,62,2019-11-28 08:27:26.042788760-05:00,True,True
47,47,VPK2,BD,0.675249,West,2,226,61,2019-11-28 08:30:31.847896860-05:00,True,True
48,48,MST2,BD,0.286629,West,2,226,60,2019-11-28 08:32:08.532585860-05:00,True,True
49,49,WDB2,BD,0.000000,West,2,226,59,2019-11-28 08:33:51.334718-05:00,True,True
50,50,COX2,BD,0.234462,West,2,226,58,2019-11-28 08:35:05.403976280-05:00,True,True
51,51,GWD2,BD,0.712177,West,2,226,57,2019-11-28 08:36:34.062774380-05:00,True,True
52,52,DON2,BD,0.969498,West,2,226,56,2019-11-28 08:37:49.502135720-05:00,True,NaN
53,53,PAP2,BD,0.954282,West,2,226,55,2019-11-28 08:38:48.595575280-05:00,True,NaN

In [25]:
train = departure_trip.merge(arrival_trip[['index', 'arr_stn_char', 'arr_time']]).rename(
    columns = {'index':'sequence'})[['sequence','dep_stn_char', 'arr_stn_char', 'subwayline', 'trainid',
                                         'trip', 'dep_time', 'arr_time']]

In [27]:
train.head(60)

,sequence,dep_stn_char,arr_stn_char,subwayline,trainid,trip,dep_time,arr_time
0,1,SGL2,BSP2,BD,226,0,2019-11-28 07:01:43.520217-05:00,2019-11-28 07:02:17.764470240-05:00
1,2,BSP2,BAT2,BD,226,0,2019-11-28 07:02:43.566018-05:00,2019-11-28 07:03:25.581713520-05:00
2,3,BAT2,CHR2,BD,226,0,2019-11-28 07:03:43.471735-05:00,2019-11-28 07:04:43.084502760-05:00
3,4,CHR2,OSS2,BD,226,0,2019-11-28 07:04:43.710364-05:00,2019-11-28 07:06:06.270735-05:00
4,5,OSS2,DUF2,BD,226,0,2019-11-28 07:06:06.270735-05:00,2019-11-28 07:07:43.672878-05:00
5,6,DUF2,LAN2,BD,226,0,2019-11-28 07:07:43.672878-05:00,2019-11-28 07:08:34.422911620-05:00
6,7,LAN2,DNW2,BD,226,0,2019-11-28 07:08:43.564186-05:00,2019-11-28 07:09:51.429448-05:00
7,8,DNW2,KEL2,BD,226,0,2019-11-28 07:09:51.429448-05:00,2019-11-28 07:11:27.229526620-05:00
8,9,KEL2,HPK2,BD,226,0,2019-11-28 07:11:43.534981-05:00,2019-11-28 07:12:43.505560-05:00
9,10,HPK2,RUN2,BD,226,0,2019-11-28 07:12:43.505560-05:00,2019-11-28 07:13:43.684322-05:00
10,11,RUN2,JNE2,BD,226,0,2019-11-28 07:13:43.684322-05:00,2019-11-28 07:15:22.554060760-05:00
11,12,JNE2,OML2,BD,226,0,2019-11-28 07:15:22.554060760-05:00,2019-11-28 07:16:43.597419-05:00
12,13,OML2,RYK2,BD,226,0,2019-11-28 07:25:59.432470-05:00,2019-11-28 07:18:51.439817-05:00
13,14,RYK2,ISL2,BD,226,0,2019-11-28 07:27:50.445717-05:00,2019-11-28 07:21:43.450338-05:00
14,15,ISL2,KIP2,BD,226,0,2019-11-28 07:30:43.559876-05:00,2019-11-28 07:33:59.230275859-05:00
15,16,KIP2,KIP1,BD,226,1,2019-11-28 07:33:59.230275859-05:00,2019-11-28 07:33:59.230275859-05:00
16,17,KIP1,ISL1,BD,226,1,2019-11-28 07:36:43.692876-05:00,2019-11-28 07:39:12.566609240-05:00
17,18,ISL1,RYK1,BD,226,1,2019-11-28 07:39:12.566609240-05:00,2019-11-28 07:41:22.271913140-05:00
18,19,RYK1,OML1,BD,226,1,2019-11-28 07:41:22.271913140-05:00,2019-11-28 07:43:48.950452480-05:00
19,20,OML1,JNE1,BD,226,1,2019-11-28 07:43:48.950452480-05:00,2019-11-28 07:44:50.460964-05:00
20,21,JNE1,RUN1,BD,226,1,2019-11-28 07:44:50.460964-05:00,2019-11-28 07:46:03.354929240-05:00
21,22,RUN1,HPK1,BD,226,1,2019-11-28 07:46:43.420956-05:00,2019-11-28 07:47:43.892868-05:00
22,23,HPK1,KEL1,BD,226,1,2019-11-28 07:47:43.892868-05:00,2019-11-28 07:48:43.442220-05:00
23,24,KEL1,DNW1,BD,226,1,2019-11-28 07:48:43.442220-05:00,2019-11-28 07:50:18.974181520-05:00
24,25,DNW1,LAN1,BD,226,1,2019-11-28 07:50:43.468234-05:00,2019-11-28 07:51:43.497170-05:00
25,26,LAN1,DUF1,BD,226,1,2019-11-28 07:51:43.497170-05:00,2019-11-28 07:52:58.063850760-05:00
26,27,DUF1,OSS1,BD,226,1,2019-11-28 07:53:51.321922-05:00,2019-11-28 07:54:43.531960-05:00
27,28,OSS1,CHR1,BD,226,1,2019-11-28 07:54:43.531960-05:00,2019-11-28 07:56:27.460560-05:00
28,29,CHR1,BAT1,BD,226,1,2019-11-28 07:56:51.323901-05:00,2019-11-28 07:58:01.194801380-05:00
29,30,BAT1,BSP1,BD,226,1,2019-11-28 07:58:01.194801380-05:00,2019-11-28 07:59:25.738037280-05:00
30,31,BSP1,SGL1,BD,226,1,2019-11-28 07:59:43.410020-05:00,2019-11-28 08:00:39.436358240-05:00
31,32,SGL1,BAU1,BD,226,1,2019-11-28 08:00:43.592003-05:00,2019-11-28 08:02:19.617056720-05:00
32,33,BAU1,YNG1,BD,226,1,2019-11-28 08:02:51.324397-05:00,2019-11-28 08:03:40.491852240-05:00
33,34,YNG1,SHE1,BD,226,1,2019-11-28 08:03:43.596314-05:00,2019-11-28 08:05:30.417116100-05:00
34,35,SHE1,CFK1,BD,226,1,2019-11-28 08:05:51.324787-05:00,2019-11-28 08:06:55.263399140-05:00
35,36,CFK1,BRD1,BD,226,1,2019-11-28 08:06:55.263399140-05:00,2019-11-28 08:08:51.326027-05:00
36,37,BRD1,CHE1,BD,226,1,2019-11-28 08:08:51.326027-05:00,2019-11-28 08:10:51.326328-05:00
37,38,CHE1,PAP1,BD,226,1,2019-11-28 08:10:51.326328-05:00,2019-11-28 08:11:50.983914280-05:00
38,39,PAP1,DON1,BD,226,1,2019-11-28 08:11:51.326711-05:00,2019-11-28 08:12:49.087334140-05:00
39,40,DON1,GWD1,BD,226,1,2019-11-28 08:12:51.321361-05:00,2019-11-28 08:13:51.320546-05:00
40,41,GWD1,COX1,BD,226,1,2019-11-28 08:13:51.320546-05:00,2019-11-28 08:15:10.318919620-05:00
41,42,COX1,WDB1,BD,226,1,2019-11-28 08:15:10.318919620-05:00,2019-11-28 08:16:51.327709-05:00
42,43,WDB1,MST1,BD,226,1,2019-11-28 08:16:51.327709-05:00,2019-11-28 08:18:42.885787280-05:00
43,44,MST1,VPK1,BD,226,1,2019-11-28 08:18:42.885787280-05:00,2019-11-28 08:19:51.327655-05:00
44,45,VPK1,KEN2,BD,226,1,2019-11-28 08:19:51.327655-05:00,2019-11-28 08:21:51.328501-05:00
45,46,KEN2,WAR2,BD,226,2,2019-11-28 08:23:51.329394-05:00,2019-11-28 08:27:26.042788760-05:00
46,47,WAR2,VPK2,BD,226,2,2019-11-28 08:27:26.042788760-05:00,2019-11-28 08:30:31.847896860-05:00
47,48,VPK2,MST2,BD,226,2,2019-11-28 08:30:31.847896860-05:00,2019-11-28 08:32:08.532585860-05:00
48,49,MST2,WDB2,BD,226,2,2019-11-28 08:32:08.532585860-05:00,2019-11-28 08:33:51.334718-05:00
49,50,WDB2,COX2,BD,226,2,2019-11-28 08:33:51.334718-05:00,2019-11-28 08:35:05.403976280-05:00
50,51,COX2,GWD2,BD,226,2,2019-11-28 08:35:05.403976280-05:00,2019-11-28 08:36:34.062774380-05:00
51,52,GWD2,DON2,BD,226,2,2019-11-28 08:36:34.062774380-05:00,2019-11-28 08:37:49.502135720-05:00
52,53,DON2,PAP2,BD,226,2,2019-11-28 08:37:51.332631-05:00,2019-11-28 08:38:48.595575280-05:00