In [23]:
import pandas as pd
import numpy as np
import datetime

In [24]:
df = pd.read_csv('cleaned_subway/raw_subway_2019-11-28_AM.csv')

In [25]:
df['request_date'] = pd.to_datetime(df['request_date'])

In [26]:
df = df.sort_values(by = 'timint')

In [27]:
df['platformid'] = df['station_char'].str[3]

In [28]:
df

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid
96041,2305871,34246572163,YIE1,SHEP,0.000000,East,463,AtStation,64,4,2019-11-28 08:25:51,32685,2019-11-28 08:25:51.333503-05:00,2019-11-28,8,3,AM,1
70449,2284190,34250776188,DNW1,BD,0.000000,East,238,AtStation,41,2,2019-11-28 11:47:46,32390,2019-11-28 11:47:43.252615-05:00,2019-11-28,11,3,AM,1
108705,2317542,34249245226,DAV1,YUS,0.000000,North,23,AtStation,26,1,2019-11-28 10:33:44,32845,2019-11-28 10:33:43.807289-05:00,2019-11-28,10,3,AM,1
130034,2331258,34250039928,STP1,YUS,0.000000,North,142,AtStation,13,1,2019-11-28 11:11:43,33032,2019-11-28 11:11:43.844225-05:00,2019-11-28,11,3,AM,1
20763,2253499,34248521900,YNG2,BD,0.000000,West,209,AtStation,22,1,2019-11-28 09:58:44,31970,2019-11-28 09:58:43.613983-05:00,2019-11-28,9,3,AM,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131973,2332904,34246290251,PVL2,YUS,23.830480,South,101,Arriving,78,1,2019-11-28 08:11:46,33054,2019-11-28 08:11:43.647875-05:00,2019-11-28,8,3,AM,2
43569,2267264,34246374797,YUN2,YUS,24.054304,South,102,Arriving,77,1,2019-11-28 08:15:46,32158,2019-11-28 08:15:43.330515-05:00,2019-11-28,8,3,AM,2
80650,2293189,34246332696,HWY2,YUS,24.077273,South,101,Arriving,79,1,2019-11-28 08:13:46,32513,2019-11-28 08:13:43.803495-05:00,2019-11-28,8,3,AM,2
27515,2257777,34246271179,PVL2,YUS,25.284794,South,101,Arriving,78,1,2019-11-28 08:10:55,32029,2019-11-28 08:10:51.335830-05:00,2019-11-28,8,3,AM,2
26169,2257206,34246227351,YUN2,YUS,26.226955,South,101,Arriving,77,1,2019-11-28 08:08:43,32021,2019-11-28 08:08:43.525283-05:00,2019-11-28,8,3,AM,2

# Filtering for only the most recent data in a request

Since each request has multiple train arrival times.

We're filtering on `station_char` and `requestid`. This might cause an issue with terminus, but we'll deal with it later.

In [29]:
df_newest = df.drop_duplicates(subset = ['requestid', 'station_char'])

In [30]:
df_newest[df_newest['station_char'] == 'KIP1'].sort_values(by = 'request_date').head(30)

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid
48032,2269017,34244782417,KIP1,BD,0.604911,West,213,Arriving,33,2,2019-11-28 07:00:47,32182,2019-11-28 07:00:43.976162-05:00,2019-11-28,7,3,AM,1
60102,2278021,34244803350,KIP1,BD,0.000000,East,213,AtStation,33,2,2019-11-28 07:01:44,32306,2019-11-28 07:01:43.534795-05:00,2019-11-28,7,3,AM,1
16818,2249606,34244827162,KIP1,BD,0.000000,East,213,AtStation,33,2,2019-11-28 07:02:47,31917,2019-11-28 07:02:43.576920-05:00,2019-11-28,7,3,AM,1
120372,2325106,34244846809,KIP1,BD,1.273126,West,215,Arriving,33,2,2019-11-28 07:03:46,32948,2019-11-28 07:03:43.456933-05:00,2019-11-28,7,3,AM,1
117256,2322606,34244867650,KIP1,BD,0.512303,East,215,Arriving,33,2,2019-11-28 07:04:46,32914,2019-11-28 07:04:43.696777-05:00,2019-11-28,7,3,AM,1
99405,2308182,34244889783,KIP1,BD,0.000000,East,215,AtStation,33,2,2019-11-28 07:05:44,32717,2019-11-28 07:05:43.659269-05:00,2019-11-28,7,3,AM,1
34657,2261607,34244912528,KIP1,BD,0.000000,East,215,AtStation,33,2,2019-11-28 07:06:45,32081,2019-11-28 07:06:43.531235-05:00,2019-11-28,7,3,AM,1
45810,2268129,34244932324,KIP1,BD,0.000000,East,215,AtStation,33,2,2019-11-28 07:07:42,32170,2019-11-28 07:07:43.660882-05:00,2019-11-28,7,3,AM,1
101625,2311184,34244953520,KIP1,BD,0.440788,West,217,Arriving,33,2,2019-11-28 07:08:46,32758,2019-11-28 07:08:43.561103-05:00,2019-11-28,7,3,AM,1
72189,2286092,34244977459,KIP1,BD,0.000000,East,217,AtStation,33,2,2019-11-28 07:09:54,32416,2019-11-28 07:09:51.436780-05:00,2019-11-28,7,3,AM,1
82447,2295327,34244994204,KIP1,BD,0.000000,East,217,AtStation,33,2,2019-11-28 07:10:42,32542,2019-11-28 07:10:43.603287-05:00,2019-11-28,7,3,AM,1
23946,2256545,34245017957,KIP1,BD,0.000000,East,217,AtStation,33,2,2019-11-28 07:11:47,32012,2019-11-28 07:11:43.518989-05:00,2019-11-28,7,3,AM,1
132883,2333351,34245040143,KIP1,BD,0.604911,West,219,Arriving,33,2,2019-11-28 07:12:47,33060,2019-11-28 07:12:43.503487-05:00,2019-11-28,7,3,AM,1
52951,2273419,34245060712,KIP1,BD,0.000000,East,219,AtStation,33,2,2019-11-28 07:13:46,32243,2019-11-28 07:13:43.682453-05:00,2019-11-28,7,3,AM,1
59656,2277606,34245081470,KIP1,BD,0.000000,East,219,AtStation,33,2,2019-11-28 07:14:48,32300,2019-11-28 07:14:43.678859-05:00,2019-11-28,7,3,AM,1
7877,2242570,34245103985,KIP1,BD,1.273126,West,221,Arriving,33,2,2019-11-28 07:15:47,31821,2019-11-28 07:15:43.578453-05:00,2019-11-28,7,3,AM,1
95392,2305692,34245124949,KIP1,BD,0.256149,East,221,Arriving,33,2,2019-11-28 07:16:43,32683,2019-11-28 07:16:43.596174-05:00,2019-11-28,7,3,AM,1
132435,2332981,34245148492,KIP1,BD,0.000000,East,221,AtStation,33,2,2019-11-28 07:17:46,33055,2019-11-28 07:17:43.408500-05:00,2019-11-28,7,3,AM,1
53840,2274355,34245171510,KIP1,BD,0.000000,East,221,AtStation,33,2,2019-11-28 07:18:53,32256,2019-11-28 07:18:51.440586-05:00,2019-11-28,7,3,AM,1
74866,2287408,34245192271,KIP1,BD,0.000000,East,221,AtStation,33,2,2019-11-28 07:19:59,32434,2019-11-28 07:19:59.426707-05:00,2019-11-28,7,3,AM,1
44924,2267760,34245212626,KIP1,BD,2.823427,West,226,Arriving,33,2,2019-11-28 07:20:54,32165,2019-11-28 07:20:51.445349-05:00,2019-11-28,7,3,AM,1
48481,2269461,34245231597,KIP1,BD,2.422204,West,226,Arriving,33,2,2019-11-28 07:21:46,32188,2019-11-28 07:21:43.449989-05:00,2019-11-28,7,3,AM,1
117703,2323263,34245252184,KIP1,BD,1.273126,West,25,Arriving,33,2,2019-11-28 07:22:42,32923,2019-11-28 07:22:43.489851-05:00,2019-11-28,7,3,AM,1
93160,2303952,34245274963,KIP1,BD,0.000000,East,25,AtStation,33,2,2019-11-28 07:23:47,32659,2019-11-28 07:23:44.111042-05:00,2019-11-28,7,3,AM,1
73966,2286743,34245296163,KIP1,BD,1.273126,West,224,Arriving,33,2,2019-11-28 07:24:52,32425,2019-11-28 07:24:51.444872-05:00,2019-11-28,7,3,AM,1
111014,2318801,34245317689,KIP1,BD,0.604911,West,224,Arriving,33,2,2019-11-28 07:25:48,32862,2019-11-28 07:25:43.835381-05:00,2019-11-28,7,3,AM,1
52504,2272904,34245337827,KIP1,BD,1.273126,West,227,Arriving,33,2,2019-11-28 07:26:47,32236,2019-11-28 07:26:43.775705-05:00,2019-11-28,7,3,AM,1
102959,2313006,34245361626,KIP1,BD,0.000000,East,227,AtStation,33,2,2019-11-28 07:27:53,32783,2019-11-28 07:27:50.446513-05:00,2019-11-28,7,3,AM,1
1138,2238290,34245379905,KIP1,BD,0.000000,East,227,AtStation,33,2,2019-11-28 07:28:46,31763,2019-11-28 07:28:43.575102-05:00,2019-11-28,7,3,AM,1
40460,2264987,34245402713,KIP1,BD,0.000000,East,227,AtStation,33,2,2019-11-28 07:29:54,32127,2019-11-28 07:29:51.452551-05:00,2019-11-28,7,3,AM,1

In [31]:
df_newest[['trainid']].drop_duplicates()

        trainid
96041       463
70449       238
108705       23
130034      142
20763       209
...         ...
115229       28
117710       22
8810        762
121716       39
14671       563

[173 rows x 1 columns]

In [32]:
single_train = df_newest[df_newest['trainid'] == 131]

In [33]:
single_train['estimated_arrival'] = single_train['request_date'] + pd.to_timedelta(single_train['timint'], 'm')

/var/folders/zw/x46df3ms6r5391lyb_y98z600000gn/T/ipykernel_9075/1386873350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  single_train['estimated_arrival'] = single_train['request_date'] + pd.to_timedelta(single_train['timint'], 'm')

In [34]:
single_train = single_train.sort_values(by = 'request_date')
#single_train.head(20)

## Creating Trip Ids for Each Train

Terminus are not represented in each trip (ie, its not guaranteed Kipling will show up in the trip)

Trip Ids are only used for the purpose of cleaning up the data, not for any analysis/graph building.

In [35]:
single_train['trip'] = (single_train['traindirection'] != single_train['traindirection'].shift(1)).cumsum()

In [36]:
single_train.groupby('trip').count()

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid,estimated_arrival
trip,,,,,,,,,,,,,,,,,,,
1,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94
2,172,172,172,172,172,172,172,172,172,172,172,172,172,172,172,172,172,172,172

In [62]:
single_train[single_train['trip'] == 2].iloc[100:150]

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,create_date,pollid,request_date,date,hour,dow,period,platformid,estimated_arrival,trip
97639,2306504,34248311790,VMC2,YUS,0.000000,South,131,AtStation,80,1,2019-11-28 09:48:47,32694,2019-11-28 09:48:43.614963-05:00,2019-11-28,9,3,AM,2,2019-11-28 09:48:43.614963-05:00,2
126061,2328312,34250138410,STA2,YUS,0.963883,South,131,Arriving,15,1,2019-11-28 11:16:44,32992,2019-11-28 11:16:43.296777-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:17:41.129780280-05:00,2
126067,2328313,34250138407,UNI2,YUS,0.000000,South,131,AtStation,16,1,2019-11-28 11:16:44,32992,2019-11-28 11:16:43.301351-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:16:43.301351-05:00,2
22035,2255857,34250158759,OSG2,YUS,1.683530,South,131,Arriving,14,1,2019-11-28 11:17:43,32003,2019-11-28 11:17:43.364378-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:19:24.376156520-05:00,2
22041,2255858,34250158756,STA2,YUS,0.963883,South,131,Arriving,15,1,2019-11-28 11:17:43,32003,2019-11-28 11:17:43.364719-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:18:41.197722280-05:00,2
22047,2255859,34250158753,UNI2,YUS,0.000000,South,131,AtStation,16,1,2019-11-28 11:17:43,32003,2019-11-28 11:17:43.365077-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:17:43.365077-05:00,2
110417,2318491,34250178952,STP2,YUS,1.962764,South,131,Arriving,13,1,2019-11-28 11:18:43,32858,2019-11-28 11:18:43.602512-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:20:41.368362140-05:00,2
110423,2318492,34250178949,OSG2,YUS,1.181165,South,131,Arriving,14,1,2019-11-28 11:18:43,32858,2019-11-28 11:18:43.602855-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:19:54.472759860-05:00,2
110429,2318493,34250178946,STA2,YUS,0.461519,South,131,Arriving,15,1,2019-11-28 11:18:43,32858,2019-11-28 11:18:43.603194-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:19:11.294323620-05:00,2
44326,2267586,34250197482,QPK2,YUS,2.692686,South,131,Arriving,12,1,2019-11-28 11:19:43,32163,2019-11-28 11:19:43.357358-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:22:24.918533240-05:00,2
44332,2267587,34250197479,STP2,YUS,1.501245,South,131,Arriving,13,1,2019-11-28 11:19:43,32163,2019-11-28 11:19:43.357699-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:21:13.432419520-05:00,2
44338,2267588,34250197892,OSG2,YUS,0.719646,South,131,Arriving,14,1,2019-11-28 11:19:44,32163,2019-11-28 11:19:43.358039-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:20:26.536814240-05:00,2
44344,2267589,34250197473,STA2,YUS,0.000000,South,131,AtStation,15,1,2019-11-28 11:19:43,32163,2019-11-28 11:19:43.358378-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:19:43.358378-05:00,2
63091,2280112,34250218276,QPK2,YUS,1.973040,South,131,Arriving,12,1,2019-11-28 11:20:43,32335,2019-11-28 11:20:43.518819-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:22:41.901219-05:00,2
63097,2280113,34250218590,STP2,YUS,0.781599,South,131,Arriving,13,1,2019-11-28 11:20:44,32335,2019-11-28 11:20:43.519158-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:21:30.415103280-05:00,2
63103,2280114,34250218587,OSG2,YUS,0.000000,South,131,AtStation,14,1,2019-11-28 11:20:44,32335,2019-11-28 11:20:43.523823-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:20:43.523823-05:00,2
29149,2259146,34250240757,MUS2,YUS,2.509766,South,131,Arriving,11,1,2019-11-28 11:21:44,32048,2019-11-28 11:21:43.733694-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:24:14.319653580-05:00,2
29155,2259147,34250241048,QPK2,YUS,1.191441,South,131,Arriving,12,1,2019-11-28 11:21:44,32048,2019-11-28 11:21:43.734033-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:22:55.220487720-05:00,2
29161,2259148,34250241045,STP2,YUS,0.000000,South,131,AtStation,13,1,2019-11-28 11:21:44,32048,2019-11-28 11:21:43.734374-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:21:43.734374-05:00,2
23352,2256296,34250263794,MUS2,YUS,1.318325,South,131,Arriving,11,1,2019-11-28 11:22:43,32009,2019-11-28 11:22:43.340432-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:24:02.439936860-05:00,2
23358,2256297,34250263791,QPK2,YUS,0.000000,South,131,AtStation,12,1,2019-11-28 11:22:43,32009,2019-11-28 11:22:43.340769-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:22:43.340769-05:00,2
101889,2311944,34250284726,SGU2,YUS,2.527935,South,131,Arriving,10,1,2019-11-28 11:23:44,32769,2019-11-28 11:23:43.673993-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:15.350084180-05:00,2
101904,2311945,34250284511,MUS2,YUS,1.318325,South,131,Arriving,11,1,2019-11-28 11:23:44,32769,2019-11-28 11:23:43.674332-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:25:02.773836860-05:00,2
101910,2311946,34250284720,QPK2,YUS,0.000000,South,131,AtStation,12,1,2019-11-28 11:23:44,32769,2019-11-28 11:23:43.674695-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:23:43.674695-05:00,2
102154,2311988,34250287056,SGU2,YUS,2.292522,South,131,Arriving,48,2,2019-11-28 11:23:52,32769,2019-11-28 11:23:51.620501-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:09.171810440-05:00,2
57687,2276690,34250304739,SGU2,YUS,1.209610,South,131,Arriving,10,1,2019-11-28 11:24:43,32288,2019-11-28 11:24:43.858661-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:25:56.435247320-05:00,2
57702,2276691,34250304736,MUS2,YUS,0.000000,South,131,AtStation,11,1,2019-11-28 11:24:43,32288,2019-11-28 11:24:43.859019-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:24:43.859019-05:00,2
57956,2276734,34250307700,SGU2,YUS,1.209610,South,131,Arriving,48,2,2019-11-28 11:24:52,32288,2019-11-28 11:24:51.620010-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:04.196596320-05:00,2
57944,2276733,34250307703,SPA2,YUS,2.427857,South,131,Arriving,47,2,2019-11-28 11:24:52,32288,2019-11-28 11:24:51.620453-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:27:17.291884940-05:00,2
35804,2262020,34250326470,SPA2,YUS,1.973348,South,131,Arriving,9,1,2019-11-28 11:25:44,32087,2019-11-28 11:25:43.712375-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:27:42.113279240-05:00,2
35816,2262021,34250326467,SGU2,YUS,0.755101,South,131,Arriving,10,1,2019-11-28 11:25:44,32087,2019-11-28 11:25:43.712718-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:29.018776620-05:00,2
36081,2262065,34250329374,SGU2,YUS,0.755101,South,131,Arriving,48,2,2019-11-28 11:25:51,32087,2019-11-28 11:25:51.637967-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:36.944025620-05:00,2
36069,2262064,34250329377,SPA2,YUS,1.973348,South,131,Arriving,47,2,2019-11-28 11:25:51,32087,2019-11-28 11:25:51.638335-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:27:50.039239240-05:00,2
25554,2257105,34250348846,DUP2,YUS,2.257189,South,131,Arriving,8,1,2019-11-28 11:26:42,32020,2019-11-28 11:26:43.380658-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:28:58.812001300-05:00,2
25557,2257106,34250348843,SPA2,YUS,1.218247,South,131,Arriving,9,1,2019-11-28 11:26:42,32020,2019-11-28 11:26:43.381019-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:27:56.475864620-05:00,2
25569,2257107,34250348840,SGU2,YUS,0.000000,South,131,AtStation,10,1,2019-11-28 11:26:42,32020,2019-11-28 11:26:43.381374-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:43.381374-05:00,2
25827,2257151,34250352155,SGU2,YUS,0.000000,South,131,AtStation,48,2,2019-11-28 11:26:51,32020,2019-11-28 11:26:50.620625-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:26:50.620625-05:00,2
25815,2257150,34250352408,SPA2,YUS,1.218247,South,131,Arriving,47,2,2019-11-28 11:26:51,32020,2019-11-28 11:26:50.621004-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:28:03.715849620-05:00,2
17959,2251124,34250372322,DUP2,YUS,1.823769,South,131,Arriving,8,1,2019-11-28 11:27:44,31938,2019-11-28 11:27:43.617684-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:29:33.043823400-05:00,2
17962,2251125,34250372319,SPA2,YUS,0.784827,South,131,Arriving,9,1,2019-11-28 11:27:44,31938,2019-11-28 11:27:43.618024-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:28:30.707665720-05:00,2
18232,2251169,34250375912,SPA2,YUS,0.784827,South,131,Arriving,47,2,2019-11-28 11:27:53,31938,2019-11-28 11:27:51.622054-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:28:38.711695720-05:00,2
70663,2285030,34250391033,DUP2,YUS,1.038942,South,131,Arriving,8,1,2019-11-28 11:28:44,32402,2019-11-28 11:28:43.526473-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:29:45.862970740-05:00,2
70666,2285031,34250391030,SPA2,YUS,0.000000,South,131,AtStation,9,1,2019-11-28 11:28:44,32402,2019-11-28 11:28:43.526821-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:28:43.526821-05:00,2
70933,2285075,34250393734,SPA2,YUS,0.000000,South,131,AtStation,47,2,2019-11-28 11:28:52,32402,2019-11-28 11:28:50.625177-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:28:50.625177-05:00,2
127762,2329480,34250411285,SCW2,YUS,2.755750,South,131,Arriving,7,1,2019-11-28 11:29:44,33008,2019-11-28 11:29:43.792564-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:32:29.137562020-05:00,2
127768,2329481,34250411282,DUP2,YUS,0.000000,South,131,AtStation,8,1,2019-11-28 11:29:44,33008,2019-11-28 11:29:43.792907-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:29:43.792907-05:00,2
65736,2281433,34250433396,SCW2,YUS,2.142450,South,131,Arriving,7,1,2019-11-28 11:30:43,32353,2019-11-28 11:30:43.536365-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:32:52.083335660-05:00,2
105909,2316501,34250453409,SCW2,YUS,1.023010,South,131,Arriving,7,1,2019-11-28 11:31:45,32831,2019-11-28 11:31:43.494613-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:32:44.875199320-05:00,2
126888,2328451,34250473822,SCW2,YUS,0.000000,South,131,AtStation,7,1,2019-11-28 11:32:42,32994,2019-11-28 11:32:43.510061-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:32:43.510061-05:00,2
39809,2264806,34250512688,CVL2,YUS,3.623961,South,131,Arriving,6,1,2019-11-28 11:34:43,32125,2019-11-28 11:34:43.638994-05:00,2019-11-28,11,3,AM,2,2019-11-28 11:38:21.076648720-05:00,2

In [45]:
single_train[single_train['trip'] == 4].iloc[0:2]

Empty DataFrame
Columns: [requestid, id, station_char, subwayline, timint, traindirection, trainid, train_message, stationid, lineid, create_date, pollid, request_date, date, hour, dow, period, platformid, estimated_arrival, trip]
Index: []

In [46]:
single_trip = single_train[single_train['trip'] == 2].copy()

## Setting Arrival Times

Must select latest possible request that the train isn't arrived at the station, for a "best guess" of when a train arrives at a station. If a station doesn't have that time, then we need to take the earliest time a station is waiting at a station.

If earlier requests show an earlier arrival time, ignore as that means the train was delayed, and the latest request will show an updated/delayed arrival time.

API runs once per minute, so the error is limited to minute resolution

In [47]:
arrivals = single_trip[['station_char']].drop_duplicates()

In [48]:
arrival_max = single_trip[single_trip['timint']!=0]
arrival_max = arrival_max.sort_values(by = 'request_date', ascending = False)
arrival_max = arrival_max.drop_duplicates(subset = ['station_char'])[['station_char', 'estimated_arrival']]

In [49]:
arrival_max[arrival_max['station_char'] == 'LWW2']

      station_char                   estimated_arrival
36226         LWW2 2019-11-28 11:40:12.011488320-05:00

In [50]:
arrivals_at_station = single_trip[single_trip['timint']==0]
arrivals_at_station = arrivals_at_station.sort_values(by = 'estimated_arrival')
arrivals_at_station  = arrivals_at_station.drop_duplicates(subset = ['station_char'])[['station_char', 'estimated_arrival']]

In [51]:
arrivals = arrivals.merge(arrival_max, how = 'left')

In [52]:
arrivals_at_station = arrivals_at_station.rename(columns = {'estimated_arrival':'at_station_time'})
arrivals = arrivals.merge(arrivals_at_station, how = 'left')
arrivals['arrival'] = True
arrivals

,station_char,estimated_arrival,at_station_time,arrival
0,NYC2,2019-11-28 08:22:05.463082900-05:00,2019-11-28 08:21:43.525918-05:00,True
1,SHP2,2019-11-28 08:23:31.705045280-05:00,2019-11-28 08:23:43.431374-05:00,True
2,YKM2,2019-11-28 08:27:14.180442819-05:00,2019-11-28 08:25:51.348639-05:00,True
3,LAW2,2019-11-28 08:29:32.112536-05:00,2019-11-28 08:29:43.571867-05:00,True
4,EGL2,2019-11-28 08:35:23.180085180-05:00,2019-11-28 08:34:43.691356-05:00,True
5,DAV2,2019-11-28 08:37:14.989708720-05:00,NaT,True
6,STC2,2019-11-28 08:39:07.925062100-05:00,2019-11-28 08:39:43.614147-05:00,True
7,SUM2,2019-11-28 08:41:11.922359720-05:00,2019-11-28 08:40:43.432227-05:00,True
8,ROS2,2019-11-28 08:42:08.055446-05:00,NaT,True
9,BLO2,2019-11-28 08:43:59.510495540-05:00,2019-11-28 08:43:43.652530-05:00,True
10,WEL2,2019-11-28 08:45:43.491160360-05:00,2019-11-28 08:45:43.660694-05:00,True
11,COL2,2019-11-28 08:48:01.387054920-05:00,2019-11-28 08:48:43.492615-05:00,True
12,DUN2,2019-11-28 08:49:37.655101720-05:00,2019-11-28 08:49:43.717700-05:00,True
13,QUN2,2019-11-28 08:50:47.392633080-05:00,2019-11-28 08:51:43.537017-05:00,True
14,KNG2,2019-11-28 08:53:08.522024540-05:00,2019-11-28 08:53:43.475629-05:00,True
15,UNI2,2019-11-28 08:54:53.846352460-05:00,2019-11-28 08:55:43.337382-05:00,True
16,STA2,2019-11-28 11:19:11.294323620-05:00,2019-11-28 08:57:43.718142-05:00,True
17,OSG2,2019-11-28 11:20:26.536814240-05:00,2019-11-28 08:58:43.579160-05:00,True
18,STP2,2019-11-28 11:21:30.415103280-05:00,2019-11-28 08:59:43.553632-05:00,True
19,QPK2,2019-11-28 11:22:55.220487720-05:00,2019-11-28 09:01:43.768076-05:00,True
20,MUS2,2019-11-28 11:25:02.773836860-05:00,2019-11-28 09:03:43.827354-05:00,True
21,SGU2,2019-11-28 11:26:36.944025620-05:00,2019-11-28 09:05:43.624408-05:00,True
22,SPA2,2019-11-28 11:28:38.711695720-05:00,2019-11-28 09:06:50.355434-05:00,True
23,DUP2,2019-11-28 11:29:45.862970740-05:00,2019-11-28 09:08:43.327928-05:00,True
24,SCW2,2019-11-28 11:32:44.875199320-05:00,2019-11-28 09:11:43.668910-05:00,True
25,CVL2,2019-11-28 11:37:54.003788900-05:00,2019-11-28 11:36:43.344083-05:00,True
26,GCN2,2019-11-28 11:39:24.515365360-05:00,2019-11-28 09:18:43.692666-05:00,True
27,LWW2,2019-11-28 11:40:12.011488320-05:00,2019-11-28 11:40:43.400459-05:00,True
28,YKD2,2019-11-28 11:42:21.039400900-05:00,2019-11-28 09:22:43.573018-05:00,True
29,WIL2,2019-11-28 11:44:35.513067360-05:00,2019-11-28 09:24:43.613392-05:00,True
30,SHW2,2019-11-28 11:47:19.807032980-05:00,2019-11-28 11:46:43.429210-05:00,True
31,DNP2,2019-11-28 11:49:26.564943840-05:00,2019-11-28 09:29:44.219123-05:00,True
32,FIW2,2019-11-28 11:52:17.063236800-05:00,2019-11-28 09:32:43.698880-05:00,True
33,YUN2,2019-11-28 11:54:20.329709220-05:00,2019-11-28 09:35:43.600635-05:00,True
34,PVL2,2019-11-28 11:55:44.822323840-05:00,2019-11-28 09:37:43.464222-05:00,True
35,HWY2,2019-11-28 11:57:32.893253840-05:00,2019-11-28 09:40:43.426573-05:00,True
36,VMC2,NaT,2019-11-28 09:48:43.614963-05:00,True

In [53]:
arrivals['estimated_arrival'] = np.where(arrivals['estimated_arrival'].isna(), arrivals['at_station_time'], arrivals['estimated_arrival'])

Adding a conditional that if the `at station time` is earlier than the estimated arrival, then that is the new estimated arrival.

In [54]:
arrivals['estimated_arrival'] = np.where(arrivals['estimated_arrival']>arrivals['at_station_time'], arrivals['at_station_time'], arrivals['estimated_arrival'])

In [55]:
arrivals = arrivals.sort_values(by = 'estimated_arrival').reset_index(drop = True)

In [56]:
arrivals

,station_char,estimated_arrival,at_station_time,arrival
0,NYC2,2019-11-28 08:21:43.525918-05:00,2019-11-28 08:21:43.525918-05:00,True
1,SHP2,2019-11-28 08:23:31.705045280-05:00,2019-11-28 08:23:43.431374-05:00,True
2,YKM2,2019-11-28 08:25:51.348639-05:00,2019-11-28 08:25:51.348639-05:00,True
3,LAW2,2019-11-28 08:29:32.112536-05:00,2019-11-28 08:29:43.571867-05:00,True
4,EGL2,2019-11-28 08:34:43.691356-05:00,2019-11-28 08:34:43.691356-05:00,True
5,DAV2,2019-11-28 08:37:14.989708720-05:00,NaT,True
6,STC2,2019-11-28 08:39:07.925062100-05:00,2019-11-28 08:39:43.614147-05:00,True
7,SUM2,2019-11-28 08:40:43.432227-05:00,2019-11-28 08:40:43.432227-05:00,True
8,ROS2,2019-11-28 08:42:08.055446-05:00,NaT,True
9,BLO2,2019-11-28 08:43:43.652530-05:00,2019-11-28 08:43:43.652530-05:00,True
10,WEL2,2019-11-28 08:45:43.491160360-05:00,2019-11-28 08:45:43.660694-05:00,True
11,COL2,2019-11-28 08:48:01.387054920-05:00,2019-11-28 08:48:43.492615-05:00,True
12,DUN2,2019-11-28 08:49:37.655101720-05:00,2019-11-28 08:49:43.717700-05:00,True
13,QUN2,2019-11-28 08:50:47.392633080-05:00,2019-11-28 08:51:43.537017-05:00,True
14,KNG2,2019-11-28 08:53:08.522024540-05:00,2019-11-28 08:53:43.475629-05:00,True
15,UNI2,2019-11-28 08:54:53.846352460-05:00,2019-11-28 08:55:43.337382-05:00,True
16,STA2,2019-11-28 08:57:43.718142-05:00,2019-11-28 08:57:43.718142-05:00,True
17,OSG2,2019-11-28 08:58:43.579160-05:00,2019-11-28 08:58:43.579160-05:00,True
18,STP2,2019-11-28 08:59:43.553632-05:00,2019-11-28 08:59:43.553632-05:00,True
19,QPK2,2019-11-28 09:01:43.768076-05:00,2019-11-28 09:01:43.768076-05:00,True
20,MUS2,2019-11-28 09:03:43.827354-05:00,2019-11-28 09:03:43.827354-05:00,True
21,SGU2,2019-11-28 09:05:43.624408-05:00,2019-11-28 09:05:43.624408-05:00,True
22,SPA2,2019-11-28 09:06:50.355434-05:00,2019-11-28 09:06:50.355434-05:00,True
23,DUP2,2019-11-28 09:08:43.327928-05:00,2019-11-28 09:08:43.327928-05:00,True
24,SCW2,2019-11-28 09:11:43.668910-05:00,2019-11-28 09:11:43.668910-05:00,True
25,GCN2,2019-11-28 09:18:43.692666-05:00,2019-11-28 09:18:43.692666-05:00,True
26,YKD2,2019-11-28 09:22:43.573018-05:00,2019-11-28 09:22:43.573018-05:00,True
27,WIL2,2019-11-28 09:24:43.613392-05:00,2019-11-28 09:24:43.613392-05:00,True
28,DNP2,2019-11-28 09:29:44.219123-05:00,2019-11-28 09:29:44.219123-05:00,True
29,FIW2,2019-11-28 09:32:43.698880-05:00,2019-11-28 09:32:43.698880-05:00,True
30,YUN2,2019-11-28 09:35:43.600635-05:00,2019-11-28 09:35:43.600635-05:00,True
31,PVL2,2019-11-28 09:37:43.464222-05:00,2019-11-28 09:37:43.464222-05:00,True
32,HWY2,2019-11-28 09:40:43.426573-05:00,2019-11-28 09:40:43.426573-05:00,True
33,VMC2,2019-11-28 09:48:43.614963-05:00,2019-11-28 09:48:43.614963-05:00,True
34,CVL2,2019-11-28 11:36:43.344083-05:00,2019-11-28 11:36:43.344083-05:00,True
35,LWW2,2019-11-28 11:40:12.011488320-05:00,2019-11-28 11:40:43.400459-05:00,True
36,SHW2,2019-11-28 11:46:43.429210-05:00,2019-11-28 11:46:43.429210-05:00,True

In [57]:
arrivals

,station_char,estimated_arrival,at_station_time,arrival
0,NYC2,2019-11-28 08:21:43.525918-05:00,2019-11-28 08:21:43.525918-05:00,True
1,SHP2,2019-11-28 08:23:31.705045280-05:00,2019-11-28 08:23:43.431374-05:00,True
2,YKM2,2019-11-28 08:25:51.348639-05:00,2019-11-28 08:25:51.348639-05:00,True
3,LAW2,2019-11-28 08:29:32.112536-05:00,2019-11-28 08:29:43.571867-05:00,True
4,EGL2,2019-11-28 08:34:43.691356-05:00,2019-11-28 08:34:43.691356-05:00,True
5,DAV2,2019-11-28 08:37:14.989708720-05:00,NaT,True
6,STC2,2019-11-28 08:39:07.925062100-05:00,2019-11-28 08:39:43.614147-05:00,True
7,SUM2,2019-11-28 08:40:43.432227-05:00,2019-11-28 08:40:43.432227-05:00,True
8,ROS2,2019-11-28 08:42:08.055446-05:00,NaT,True
9,BLO2,2019-11-28 08:43:43.652530-05:00,2019-11-28 08:43:43.652530-05:00,True
10,WEL2,2019-11-28 08:45:43.491160360-05:00,2019-11-28 08:45:43.660694-05:00,True
11,COL2,2019-11-28 08:48:01.387054920-05:00,2019-11-28 08:48:43.492615-05:00,True
12,DUN2,2019-11-28 08:49:37.655101720-05:00,2019-11-28 08:49:43.717700-05:00,True
13,QUN2,2019-11-28 08:50:47.392633080-05:00,2019-11-28 08:51:43.537017-05:00,True
14,KNG2,2019-11-28 08:53:08.522024540-05:00,2019-11-28 08:53:43.475629-05:00,True
15,UNI2,2019-11-28 08:54:53.846352460-05:00,2019-11-28 08:55:43.337382-05:00,True
16,STA2,2019-11-28 08:57:43.718142-05:00,2019-11-28 08:57:43.718142-05:00,True
17,OSG2,2019-11-28 08:58:43.579160-05:00,2019-11-28 08:58:43.579160-05:00,True
18,STP2,2019-11-28 08:59:43.553632-05:00,2019-11-28 08:59:43.553632-05:00,True
19,QPK2,2019-11-28 09:01:43.768076-05:00,2019-11-28 09:01:43.768076-05:00,True
20,MUS2,2019-11-28 09:03:43.827354-05:00,2019-11-28 09:03:43.827354-05:00,True
21,SGU2,2019-11-28 09:05:43.624408-05:00,2019-11-28 09:05:43.624408-05:00,True
22,SPA2,2019-11-28 09:06:50.355434-05:00,2019-11-28 09:06:50.355434-05:00,True
23,DUP2,2019-11-28 09:08:43.327928-05:00,2019-11-28 09:08:43.327928-05:00,True
24,SCW2,2019-11-28 09:11:43.668910-05:00,2019-11-28 09:11:43.668910-05:00,True
25,GCN2,2019-11-28 09:18:43.692666-05:00,2019-11-28 09:18:43.692666-05:00,True
26,YKD2,2019-11-28 09:22:43.573018-05:00,2019-11-28 09:22:43.573018-05:00,True
27,WIL2,2019-11-28 09:24:43.613392-05:00,2019-11-28 09:24:43.613392-05:00,True
28,DNP2,2019-11-28 09:29:44.219123-05:00,2019-11-28 09:29:44.219123-05:00,True
29,FIW2,2019-11-28 09:32:43.698880-05:00,2019-11-28 09:32:43.698880-05:00,True
30,YUN2,2019-11-28 09:35:43.600635-05:00,2019-11-28 09:35:43.600635-05:00,True
31,PVL2,2019-11-28 09:37:43.464222-05:00,2019-11-28 09:37:43.464222-05:00,True
32,HWY2,2019-11-28 09:40:43.426573-05:00,2019-11-28 09:40:43.426573-05:00,True
33,VMC2,2019-11-28 09:48:43.614963-05:00,2019-11-28 09:48:43.614963-05:00,True
34,CVL2,2019-11-28 11:36:43.344083-05:00,2019-11-28 11:36:43.344083-05:00,True
35,LWW2,2019-11-28 11:40:12.011488320-05:00,2019-11-28 11:40:43.400459-05:00,True
36,SHW2,2019-11-28 11:46:43.429210-05:00,2019-11-28 11:46:43.429210-05:00,True

## Finding Estimated Departures

First find the latest possible time that the train is waiting at the station. If there is no data with `timint = 0`, then take the arrival time.

In [58]:
departures = single_trip[['station_char']].drop_duplicates()
departures_max = single_trip[single_trip['timint'] == 0]
departures_max = departures_max.sort_values(by = 'estimated_arrival', ascending = False)
departures_max = departures_max.drop_duplicates(subset = ['station_char'])[['station_char', 'estimated_arrival']]

In [59]:
departures = departures.merge(departures_max, how = 'left')
departures['departure'] = True
departures

   station_char                estimated_arrival  departure
0          NYC2 2019-11-28 08:21:43.525918-05:00       True
1          SHP2 2019-11-28 08:23:51.329004-05:00       True
2          YKM2 2019-11-28 08:26:43.368032-05:00       True
3          LAW2 2019-11-28 08:30:43.889204-05:00       True
4          EGL2 2019-11-28 08:34:43.691356-05:00       True
5          DAV2                              NaT       True
6          STC2 2019-11-28 08:39:43.614147-05:00       True
7          SUM2 2019-11-28 08:40:43.432227-05:00       True
8          ROS2                              NaT       True
9          BLO2 2019-11-28 08:44:43.762428-05:00       True
10         WEL2 2019-11-28 08:46:43.518824-05:00       True
11         COL2 2019-11-28 08:48:43.492615-05:00       True
12         DUN2 2019-11-28 08:49:43.717700-05:00       True
13         QUN2 2019-11-28 08:51:43.537017-05:00       True
14         KNG2 2019-11-28 08:53:43.475629-05:00       True
15         UNI2 2019-11-28 11:17:43.365077-05:00       True
16         STA2 2019-11-28 11:19:43.358378-05:00       True
17         OSG2 2019-11-28 11:20:43.523823-05:00       True
18         STP2 2019-11-28 11:21:43.734374-05:00       True
19         QPK2 2019-11-28 11:23:43.674695-05:00       True
20         MUS2 2019-11-28 11:24:43.859019-05:00       True
21         SGU2 2019-11-28 11:26:50.620625-05:00       True
22         SPA2 2019-11-28 11:28:50.625177-05:00       True
23         DUP2 2019-11-28 11:29:43.792907-05:00       True
24         SCW2 2019-11-28 11:32:43.510061-05:00       True
25         CVL2 2019-11-28 11:36:43.344083-05:00       True
26         GCN2 2019-11-28 11:38:43.539272-05:00       True
27         LWW2 2019-11-28 11:40:43.400459-05:00       True
28         YKD2 2019-11-28 09:22:43.573018-05:00       True
29         WIL2 2019-11-28 11:43:43.897222-05:00       True
30         SHW2 2019-11-28 11:46:43.429210-05:00       True
31         DNP2 2019-11-28 09:29:44.219123-05:00       True
32         FIW2 2019-11-28 11:51:43.435548-05:00       True
33         YUN2 2019-11-28 11:53:43.647321-05:00       True
34         PVL2 2019-11-28 11:55:50.651075-05:00       True
35         HWY2 2019-11-28 11:57:43.734031-05:00       True
36         VMC2 2019-11-28 09:48:43.614963-05:00       True

In [60]:
departures = departures.merge(arrivals.rename(columns = {'estimated_arrival':'before_station_time'}))

In [61]:
departures['estimated_arrival'] = np.where(departures['estimated_arrival'].isna(), departures['before_station_time'], departures['estimated_arrival'])
departures = departures[['station_char', 'estimated_arrival', 'departure']]
departures

   station_char                   estimated_arrival  departure
0          NYC2    2019-11-28 08:21:43.525918-05:00       True
1          SHP2    2019-11-28 08:23:51.329004-05:00       True
2          YKM2    2019-11-28 08:26:43.368032-05:00       True
3          LAW2    2019-11-28 08:30:43.889204-05:00       True
4          EGL2    2019-11-28 08:34:43.691356-05:00       True
5          DAV2 2019-11-28 08:37:14.989708720-05:00       True
6          STC2    2019-11-28 08:39:43.614147-05:00       True
7          SUM2    2019-11-28 08:40:43.432227-05:00       True
8          ROS2    2019-11-28 08:42:08.055446-05:00       True
9          BLO2    2019-11-28 08:44:43.762428-05:00       True
10         WEL2    2019-11-28 08:46:43.518824-05:00       True
11         COL2    2019-11-28 08:48:43.492615-05:00       True
12         DUN2    2019-11-28 08:49:43.717700-05:00       True
13         QUN2    2019-11-28 08:51:43.537017-05:00       True
14         KNG2    2019-11-28 08:53:43.475629-05:00       True
15         UNI2    2019-11-28 11:17:43.365077-05:00       True
16         STA2    2019-11-28 11:19:43.358378-05:00       True
17         OSG2    2019-11-28 11:20:43.523823-05:00       True
18         STP2    2019-11-28 11:21:43.734374-05:00       True
19         QPK2    2019-11-28 11:23:43.674695-05:00       True
20         MUS2    2019-11-28 11:24:43.859019-05:00       True
21         SGU2    2019-11-28 11:26:50.620625-05:00       True
22         SPA2    2019-11-28 11:28:50.625177-05:00       True
23         DUP2    2019-11-28 11:29:43.792907-05:00       True
24         SCW2    2019-11-28 11:32:43.510061-05:00       True
25         CVL2    2019-11-28 11:36:43.344083-05:00       True
26         GCN2    2019-11-28 11:38:43.539272-05:00       True
27         LWW2    2019-11-28 11:40:43.400459-05:00       True
28         YKD2    2019-11-28 09:22:43.573018-05:00       True
29         WIL2    2019-11-28 11:43:43.897222-05:00       True
30         SHW2    2019-11-28 11:46:43.429210-05:00       True
31         DNP2    2019-11-28 09:29:44.219123-05:00       True
32         FIW2    2019-11-28 11:51:43.435548-05:00       True
33         YUN2    2019-11-28 11:53:43.647321-05:00       True
34         PVL2    2019-11-28 11:55:50.651075-05:00       True
35         HWY2    2019-11-28 11:57:43.734031-05:00       True
36         VMC2    2019-11-28 09:48:43.614963-05:00       True

In [111]:
departures = departures.sort_values(by = 'estimated_arrival').reset_index(drop = True)

In [112]:
arrivals['previous_depart'] = departures['estimated_arrival'].shift(1)
arrivals

,station_char,estimated_arrival,at_station_time,arrival,previous_depart
0,FIN2,2019-12-02 07:55:37.481210-05:00,2019-12-02 07:55:37.481210-05:00,True,NaT
1,NYC2,2019-12-02 08:02:21.689458920-05:00,NaT,True,2019-12-02 07:58:37.361699-05:00
2,SHP2,2019-12-02 08:04:06.814839280-05:00,2019-12-02 08:04:37.545199-05:00,True,2019-12-02 08:02:21.689458920-05:00
3,YKM2,2019-12-02 08:07:31.400254280-05:00,2019-12-02 08:07:37.724352-05:00,True,2019-12-02 08:04:44.727357-05:00
4,LAW2,2019-12-02 08:10:44.742453-05:00,2019-12-02 08:10:44.742453-05:00,True,2019-12-02 08:07:37.724352-05:00
5,EGL2,2019-12-02 08:14:54.001314820-05:00,2019-12-02 08:15:37.359710-05:00,True,2019-12-02 08:10:44.742453-05:00
6,DAV2,2019-12-02 08:17:37.256454820-05:00,2019-12-02 08:17:37.629881-05:00,True,2019-12-02 08:15:37.359710-05:00
7,STC2,2019-12-02 08:21:25.050322640-05:00,2019-12-02 08:21:37.661158-05:00,True,2019-12-02 08:17:37.629881-05:00
8,SUM2,2019-12-02 08:23:33.549621180-05:00,2019-12-02 08:23:37.805803-05:00,True,2019-12-02 08:21:37.661158-05:00
9,ROS2,2019-12-02 08:27:26.081652260-05:00,2019-12-02 08:27:37.805398-05:00,True,2019-12-02 08:25:38.264912-05:00
10,BLO2,2019-12-02 08:29:22.245881560-05:00,2019-12-02 08:29:37.750153-05:00,True,2019-12-02 08:27:37.805398-05:00
11,WEL2,2019-12-02 08:31:21.874277360-05:00,2019-12-02 08:31:37.408968-05:00,True,2019-12-02 08:29:45.314377-05:00
12,COL2,2019-12-02 08:37:46.536969360-05:00,2019-12-02 08:38:37.613595-05:00,True,2019-12-02 08:35:37.445323-05:00
13,DUN2,2019-12-02 08:39:31.784218720-05:00,2019-12-02 08:39:37.837548-05:00,True,2019-12-02 08:38:37.613595-05:00
14,QUN2,2019-12-02 08:41:09.246006100-05:00,2019-12-02 08:41:37.428093-05:00,True,2019-12-02 08:39:37.837548-05:00
15,KNG2,2019-12-02 08:42:28.980979560-05:00,2019-12-02 08:42:37.730088-05:00,True,2019-12-02 08:41:37.428093-05:00
16,UNI2,2019-12-02 08:44:12.557344440-05:00,2019-12-02 08:44:37.514323-05:00,True,2019-12-02 08:42:37.730088-05:00
17,STA2,2019-12-02 08:46:51.791044100-05:00,2019-12-02 08:47:37.696244-05:00,True,2019-12-02 08:44:37.514323-05:00
18,OSG2,2019-12-02 08:48:20.965716360-05:00,2019-12-02 08:48:37.509251-05:00,True,2019-12-02 08:47:37.696244-05:00
19,STP2,2019-12-02 08:49:24.508107-05:00,2019-12-02 08:49:37.558442-05:00,True,2019-12-02 08:48:37.509251-05:00
20,QPK2,2019-12-02 08:51:33.294821460-05:00,2019-12-02 08:51:37.878220-05:00,True,2019-12-02 08:49:37.558442-05:00
21,MUS2,2019-12-02 08:53:09.974660880-05:00,2019-12-02 08:53:37.682840-05:00,True,2019-12-02 08:51:37.878220-05:00
22,SGU2,2019-12-02 08:54:45.326216-05:00,2019-12-02 08:54:45.326216-05:00,True,2019-12-02 08:53:37.682840-05:00
23,SPA2,2019-12-02 08:56:35.922471840-05:00,2019-12-02 08:56:37.801920-05:00,True,2019-12-02 08:55:37.878882-05:00
24,DUP2,2019-12-02 08:58:22.391708820-05:00,2019-12-02 08:58:37.557474-05:00,True,2019-12-02 08:56:37.834868-05:00
25,SCW2,2019-12-02 09:00:37.658710-05:00,2019-12-02 09:00:37.658710-05:00,True,2019-12-02 08:58:37.557474-05:00
26,CVL2,2019-12-02 09:05:20.919804080-05:00,NaT,True,2019-12-02 09:00:37.658710-05:00
27,GCN2,2019-12-02 09:06:37.733512-05:00,2019-12-02 09:06:37.733512-05:00,True,2019-12-02 09:05:20.919804080-05:00
28,LWW2,2019-12-02 09:08:34.837185480-05:00,2019-12-02 09:08:37.715613-05:00,True,2019-12-02 09:06:37.733512-05:00
29,YKD2,2019-12-02 09:10:37.470245-05:00,2019-12-02 09:10:37.470245-05:00,True,2019-12-02 09:08:37.715613-05:00
30,WIL2,2019-12-02 09:12:32.150665020-05:00,2019-12-02 09:12:37.695017-05:00,True,2019-12-02 09:10:37.470245-05:00
31,SHW2,2019-12-02 09:15:37.608032-05:00,2019-12-02 09:15:37.608032-05:00,True,2019-12-02 09:12:37.695017-05:00
32,YUN2,2019-12-02 09:17:16.231314740-05:00,2019-12-02 09:17:37.649417-05:00,True,2019-12-02 09:15:37.608032-05:00
33,DNP2,2019-12-02 09:18:42.987971340-05:00,NaT,True,2019-12-02 09:17:37.649417-05:00
34,PVL2,2019-12-02 09:18:59.131839340-05:00,2019-12-02 09:19:37.608962-05:00,True,2019-12-02 09:18:42.987971340-05:00
35,HWY2,2019-12-02 09:21:19.193476840-05:00,NaT,True,2019-12-02 09:19:37.608962-05:00
36,FIW2,2019-12-02 09:22:25.144163800-05:00,NaT,True,2019-12-02 09:21:19.193476840-05:00
37,VMC2,2019-12-02 09:23:35.521338120-05:00,NaT,True,2019-12-02 09:22:25.144163800-05:00
38,VMC1,2019-12-02 09:23:35.521338120-05:00,NaT,True,2019-12-02 09:23:35.521338120-05:00

In [113]:
arrivals['estimated_arrival'] = np.where(arrivals['estimated_arrival'] < arrivals['previous_depart'], 
                                         arrivals['at_station_time'], arrivals['estimated_arrival'])

In [114]:
arrivals = arrivals[['station_char', 'estimated_arrival', 'arrival']]

In [115]:
arrivals

   station_char                   estimated_arrival  arrival
0          FIN2    2019-12-02 07:55:37.481210-05:00     True
1          NYC2 2019-12-02 08:02:21.689458920-05:00     True
2          SHP2 2019-12-02 08:04:06.814839280-05:00     True
3          YKM2 2019-12-02 08:07:31.400254280-05:00     True
4          LAW2    2019-12-02 08:10:44.742453-05:00     True
5          EGL2 2019-12-02 08:14:54.001314820-05:00     True
6          DAV2 2019-12-02 08:17:37.256454820-05:00     True
7          STC2 2019-12-02 08:21:25.050322640-05:00     True
8          SUM2 2019-12-02 08:23:33.549621180-05:00     True
9          ROS2 2019-12-02 08:27:26.081652260-05:00     True
10         BLO2 2019-12-02 08:29:22.245881560-05:00     True
11         WEL2 2019-12-02 08:31:21.874277360-05:00     True
12         COL2 2019-12-02 08:37:46.536969360-05:00     True
13         DUN2 2019-12-02 08:39:31.784218720-05:00     True
14         QUN2 2019-12-02 08:41:09.246006100-05:00     True
15         KNG2 2019-12-02 08:42:28.980979560-05:00     True
16         UNI2 2019-12-02 08:44:12.557344440-05:00     True
17         STA2 2019-12-02 08:46:51.791044100-05:00     True
18         OSG2 2019-12-02 08:48:20.965716360-05:00     True
19         STP2    2019-12-02 08:49:24.508107-05:00     True
20         QPK2 2019-12-02 08:51:33.294821460-05:00     True
21         MUS2 2019-12-02 08:53:09.974660880-05:00     True
22         SGU2    2019-12-02 08:54:45.326216-05:00     True
23         SPA2 2019-12-02 08:56:35.922471840-05:00     True
24         DUP2 2019-12-02 08:58:22.391708820-05:00     True
25         SCW2    2019-12-02 09:00:37.658710-05:00     True
26         CVL2 2019-12-02 09:05:20.919804080-05:00     True
27         GCN2    2019-12-02 09:06:37.733512-05:00     True
28         LWW2 2019-12-02 09:08:34.837185480-05:00     True
29         YKD2    2019-12-02 09:10:37.470245-05:00     True
30         WIL2 2019-12-02 09:12:32.150665020-05:00     True
31         SHW2    2019-12-02 09:15:37.608032-05:00     True
32         YUN2 2019-12-02 09:17:16.231314740-05:00     True
33         DNP2 2019-12-02 09:18:42.987971340-05:00     True
34         PVL2 2019-12-02 09:18:59.131839340-05:00     True
35         HWY2 2019-12-02 09:21:19.193476840-05:00     True
36         FIW2 2019-12-02 09:22:25.144163800-05:00     True
37         VMC2 2019-12-02 09:23:35.521338120-05:00     True
38         VMC1 2019-12-02 09:23:35.521338120-05:00     True

In [116]:
single_trip = single_trip.merge(arrivals, how = 'left')
single_trip = single_trip.merge(departures, how = 'left')

In [117]:
single_trip = single_trip.sort_values(by = 'estimated_arrival')

In [118]:
#train214_2_dep = single_trip[~single_trip['departure'].isna()]
#train242_2_dep = single_trip[~single_trip['departure'].isna()]
train242_3_dep = single_trip[~single_trip['departure'].isna()]

In [126]:
#train214_3 = single_trip[~single_trip['arrival'].isna()]
#train214_2 = single_trip[~single_trip['arrival'].isna()]
#train242_2 = single_trip[~single_trip['arrival'].isna()]
train242_3 = single_trip[~single_trip['arrival'].isna()]

In [83]:
single_trip.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 3 to 52
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   requestid          53 non-null     int64
 1   id                 53 non-null     int64
 2   station_char       53 non-null     object
 3   subwayline         53 non-null     object
 4   timint             53 non-null     float64
 5   traindirection     53 non-null     object
 6   trainid            53 non-null     int64
 7   train_message      53 non-null     object
 8   stationid          53 non-null     int64
 9   lineid             53 non-null     int64
 10  create_date        53 non-null     object
 11  pollid             53 non-null     int64
 12  request_date       53 non-null     datetime64[ns, pytz.FixedOffset(-300)]
 13  date               53 non-null     object
 14  hour               53 non-null     int64
 15  dow                53 non-null     int64
 16  period             53 non-null     object
 17  platformid         53 non-null     object
 18  estimated_arrival  53 non-null     datetime64[ns, pytz.FixedOffset(-300)]
 19  trip               53 non-null     int64
 20  arrival            18 non-null     object
 21  departure          18 non-null     object
dtypes: datetime64[ns, pytz.FixedOffset(-300)](2), float64(1), int64(9), object(10)
memory usage: 9.5+ KB

In [119]:
single_trip[['station_char', 'lineid', 'timint', 'traindirection', 'trip','trainid', 'stationid', 'estimated_arrival', 'arrival', 'departure']]

,station_char,lineid,timint,traindirection,trip,trainid,stationid,estimated_arrival,arrival,departure
0,FIN2,1,0.000000,South,2,117,32,2019-12-02 07:55:37.481210-05:00,True,NaN
1,FIN2,1,0.000000,South,2,117,32,2019-12-02 07:56:37.725594-05:00,NaN,NaN
2,FIN2,1,0.000000,South,2,117,32,2019-12-02 07:57:37.879006-05:00,NaN,NaN
3,FIN2,1,0.000000,South,2,117,32,2019-12-02 07:58:37.361699-05:00,NaN,True
4,NYC2,1,1.368612,South,2,117,31,2019-12-02 08:01:59.500951900-05:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
236,VMC2,1,7.339964,South,2,117,80,2019-12-02 09:23:57.900514140-05:00,NaN,NaN
241,VMC2,1,6.694329,South,2,117,80,2019-12-02 09:24:19.310327400-05:00,NaN,NaN
242,VMC1,1,6.694329,South,2,117,80,2019-12-02 09:24:19.310327400-05:00,NaN,NaN
249,VMC1,1,4.742228,South,2,117,80,2019-12-02 09:24:22.143344780-05:00,NaN,NaN
250,VMC2,1,4.742228,South,2,117,80,2019-12-02 09:24:22.143344780-05:00,NaN,NaN

In [123]:
train242_3_dep

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,...,date,hour,dow,period,platformid,estimated_arrival,trip,arrival,previous_depart,departure
3,668726,34349620780,FIN2,YUS,0.000000,South,117,AtStation,32,1,...,2019-12-02,7,0,AM,2,2019-12-02 07:58:37.361699-05:00,2,NaN,NaT,True
5,640024,34349694129,NYC2,YUS,0.735106,South,117,Arriving,31,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:02:21.689458920-05:00,2,True,2019-12-02 07:58:37.361699-05:00,True
11,682224,34349766536,SHP2,YUS,0.000000,South,117,AtStation,64,4,...,2019-12-02,8,0,AM,2,2019-12-02 08:04:44.727357-05:00,2,NaN,NaT,True
14,666922,34349841371,YKM2,YUS,0.000000,South,117,AtStation,29,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:07:37.724352-05:00,2,NaN,NaT,True
16,701781,34349915194,LAW2,YUS,0.000000,South,117,AtStation,28,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:10:44.742453-05:00,2,True,2019-12-02 08:07:37.724352-05:00,True
19,660174,34350028898,EGL2,YUS,0.000000,South,117,AtStation,27,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:15:37.359710-05:00,2,NaN,NaT,True
21,655607,34350076429,DAV2,YUS,0.000000,South,117,AtStation,26,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:17:37.629881-05:00,2,NaN,NaT,True
26,676577,34350171607,STC2,YUS,0.000000,South,117,AtStation,25,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:21:37.661158-05:00,2,NaN,NaT,True
37,729380,34350268427,SUM2,YUS,0.000000,South,117,Delayed,24,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:25:38.264912-05:00,2,NaN,NaT,True
45,655752,34350317723,ROS2,YUS,0.000000,South,117,AtStation,23,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:27:37.805398-05:00,2,NaN,NaT,True
55,725661,34350364534,BLO2,YUS,0.000000,South,117,AtStation,50,2,...,2019-12-02,8,0,AM,2,2019-12-02 08:29:45.314377-05:00,2,NaN,NaT,True
86,710174,34350508836,WEL2,YUS,0.000000,South,117,Delayed,21,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:35:37.445323-05:00,2,NaN,NaT,True
101,647045,34350579452,COL2,YUS,0.000000,South,117,AtStation,20,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:38:37.613595-05:00,2,NaN,NaT,True
108,670831,34350602338,DUN2,YUS,0.000000,South,117,AtStation,19,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:39:37.837548-05:00,2,NaN,NaT,True
122,721435,34350647748,QUN2,YUS,0.000000,South,117,AtStation,18,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:41:37.428093-05:00,2,NaN,NaT,True
125,685711,34350673816,KNG2,YUS,0.000000,South,117,AtStation,17,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:42:37.730088-05:00,2,NaN,NaT,True
131,714168,34350720184,UNI2,YUS,0.000000,South,117,AtStation,16,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:44:37.514323-05:00,2,NaN,NaT,True
142,655892,34350798517,STA2,YUS,0.000000,South,117,AtStation,15,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:47:37.696244-05:00,2,NaN,NaT,True
146,700881,34350821801,OSG2,YUS,0.000000,South,117,AtStation,14,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:48:37.509251-05:00,2,NaN,NaT,True
149,659607,34350845376,STP2,YUS,0.000000,South,117,AtStation,13,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:49:37.558442-05:00,2,NaN,NaT,True
157,667053,34350893718,QPK2,YUS,0.000000,South,117,AtStation,12,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:51:37.878220-05:00,2,NaN,NaT,True
170,639795,34350943706,MUS2,YUS,0.000000,South,117,AtStation,11,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:53:37.682840-05:00,2,NaN,NaT,True
181,716923,34350994884,SGU2,YUS,0.000000,South,117,AtStation,10,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:55:37.878882-05:00,2,NaN,NaT,True
186,708491,34351019987,SPA2,YUS,0.000000,South,117,AtStation,47,2,...,2019-12-02,8,0,AM,2,2019-12-02 08:56:37.834868-05:00,2,NaN,NaT,True
190,717483,34351066224,DUP2,YUS,0.000000,South,117,AtStation,8,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:58:37.557474-05:00,2,NaN,NaT,True
194,666642,34351115803,SCW2,YUS,0.000000,South,117,AtStation,7,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:00:37.658710-05:00,2,True,2019-12-02 08:58:37.557474-05:00,True
204,651387,34351205961,CVL2,YUS,0.724808,South,117,Arriving,6,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:05:20.919804080-05:00,2,True,2019-12-02 09:00:37.658710-05:00,True
210,660670,34351254953,GCN2,YUS,0.000000,South,117,AtStation,5,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:06:37.733512-05:00,2,True,2019-12-02 09:05:20.919804080-05:00,True
216,686804,34351301755,LWW2,YUS,0.000000,South,117,AtStation,4,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:08:37.715613-05:00,2,NaN,NaT,True
221,647986,34351351205,YKD2,YUS,0.000000,South,117,AtStation,3,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:10:37.470245-05:00,2,True,2019-12-02 09:08:37.715613-05:00,True
225,719489,34351400699,WIL2,YUS,0.000000,South,117,AtStation,2,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:12:37.695017-05:00,2,NaN,NaT,True
230,726969,34351472882,SHW2,YUS,0.000000,South,117,AtStation,1,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:15:37.608032-05:00,2,True,2019-12-02 09:12:37.695017-05:00,True
238,702293,34351526891,YUN2,YUS,0.000000,South,117,AtStation,77,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:17:37.649417-05:00,2,NaN,NaT,True
231,727001,34351474203,DNP2,YUS,3.089306,South,117,Arriving,75,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:18:42.987971340-05:00,2,True,2019-12-02 09:17:37.649417-05:00,True
247,677585,34351576272,PVL2,YUS,0.000000,South,117,AtStation,78,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:19:37.608962-05:00,2,NaN,NaT,True
251,686764,34351602790,HWY2,YUS,0.687362,South,117,Arriving,79,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:21:19.193476840-05:00,2,True,2019-12-02 09:19:37.608962-05:00,True
232,727002,34351474427,FIW2,YUS,6.791902,South,117,Arriving,76,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:22:25.144163800-05:00,2,True,2019-12-02 09:21:19.193476840-05:00,True
257,658156,34351654478,VMC2,YUS,0.961779,South,117,Arriving,80,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:23:35.521338120-05:00,2,True,2019-12-02 09:22:25.144163800-05:00,True
256,658156,34351654481,VMC1,YUS,0.961779,South,117,Arriving,80,1,...,2019-12-02,9,0,AM,1,2019-12-02 09:23:35.521338120-05:00,2,True,2019-12-02 09:23:35.521338120-05:00,True

In [127]:
train242_3

,requestid,id,station_char,subwayline,timint,traindirection,trainid,train_message,stationid,lineid,...,date,hour,dow,period,platformid,estimated_arrival,trip,arrival,previous_depart,departure
0,652290,34349545390,FIN2,YUS,0.000000,South,117,AtStation,32,1,...,2019-12-02,7,0,AM,2,2019-12-02 07:55:37.481210-05:00,2,True,NaT,NaN
5,640024,34349694129,NYC2,YUS,0.735106,South,117,Arriving,31,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:02:21.689458920-05:00,2,True,2019-12-02 07:58:37.361699-05:00,True
9,657007,34349743234,SHP2,YUS,0.368151,South,117,Arriving,64,4,...,2019-12-02,8,0,AM,2,2019-12-02 08:04:06.814839280-05:00,2,True,2019-12-02 08:02:21.689458920-05:00,NaN
13,648086,34349816023,YKM2,YUS,0.896471,South,117,Arriving,29,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:07:31.400254280-05:00,2,True,2019-12-02 08:04:44.727357-05:00,NaN
16,701781,34349915194,LAW2,YUS,0.000000,South,117,AtStation,28,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:10:44.742453-05:00,2,True,2019-12-02 08:07:37.724352-05:00,True
18,697342,34350004905,EGL2,YUS,0.274918,South,117,Arriving,27,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:14:54.001314820-05:00,2,True,2019-12-02 08:10:44.742453-05:00,NaN
20,672303,34350052082,DAV2,YUS,0.996278,South,117,Arriving,26,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:17:37.256454820-05:00,2,True,2019-12-02 08:15:37.359710-05:00,NaN
23,715682,34350150017,STC2,YUS,0.671755,South,117,Arriving,25,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:21:25.050322640-05:00,2,True,2019-12-02 08:17:37.629881-05:00,NaN
28,690140,34350196502,SUM2,YUS,0.934122,South,117,Arriving,24,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:23:33.549621180-05:00,2,True,2019-12-02 08:21:37.661158-05:00,NaN
41,665844,34350293171,ROS2,YUS,0.808616,South,117,Arriving,23,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:27:26.081652260-05:00,2,True,2019-12-02 08:25:38.264912-05:00,NaN
50,718554,34350342438,BLO2,YUS,0.482301,South,117,Arriving,50,2,...,2019-12-02,8,0,AM,2,2019-12-02 08:29:22.245881560-05:00,2,True,2019-12-02 08:27:37.805398-05:00,NaN
59,668493,34350384837,WEL2,YUS,0.740485,South,117,Arriving,21,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:31:21.874277360-05:00,2,True,2019-12-02 08:29:45.314377-05:00,NaN
97,644299,34350557975,COL2,YUS,0.151205,South,117,Arriving,20,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:37:46.536969360-05:00,2,True,2019-12-02 08:35:37.445323-05:00,NaN
100,647044,34350579283,DUN2,YUS,0.902849,South,117,Arriving,19,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:39:31.784218720-05:00,2,True,2019-12-02 08:38:37.613595-05:00,NaN
115,644644,34350624813,QUN2,YUS,0.531308,South,117,Arriving,18,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:41:09.246006100-05:00,2,True,2019-12-02 08:39:37.837548-05:00,NaN
121,721434,34350647198,KNG2,YUS,0.859221,South,117,Arriving,17,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:42:28.980979560-05:00,2,True,2019-12-02 08:41:37.428093-05:00,NaN
128,714833,34350696660,UNI2,YUS,0.584499,South,117,Arriving,16,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:44:12.557344440-05:00,2,True,2019-12-02 08:42:37.730088-05:00,NaN
138,646966,34350771936,STA2,YUS,0.236668,South,117,Arriving,15,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:46:51.791044100-05:00,2,True,2019-12-02 08:44:37.514323-05:00,NaN
141,655891,34350798520,OSG2,YUS,0.721165,South,117,Arriving,14,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:48:20.965716360-05:00,2,True,2019-12-02 08:47:37.696244-05:00,NaN
145,700880,34350821804,STP2,YUS,0.783320,South,117,Arriving,13,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:49:24.508107-05:00,2,True,2019-12-02 08:48:37.509251-05:00,NaN
152,670234,34350869315,QPK2,YUS,0.922353,South,117,Arriving,12,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:51:33.294821460-05:00,2,True,2019-12-02 08:49:37.558442-05:00,NaN
164,672869,34350919955,MUS2,YUS,0.539745,South,117,Arriving,11,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:53:09.974660880-05:00,2,True,2019-12-02 08:51:37.878220-05:00,NaN
176,691877,34350972946,SGU2,YUS,0.000000,South,117,AtStation,48,2,...,2019-12-02,8,0,AM,2,2019-12-02 08:54:45.326216-05:00,2,True,2019-12-02 08:53:37.682840-05:00,NaN
182,716966,34350997197,SPA2,YUS,0.966784,South,117,Arriving,47,2,...,2019-12-02,8,0,AM,2,2019-12-02 08:56:35.922471840-05:00,2,True,2019-12-02 08:55:37.878882-05:00,NaN
188,693825,34351042510,DUP2,YUS,0.745118,South,117,Arriving,8,1,...,2019-12-02,8,0,AM,2,2019-12-02 08:58:22.391708820-05:00,2,True,2019-12-02 08:56:37.834868-05:00,NaN
194,666642,34351115803,SCW2,YUS,0.000000,South,117,AtStation,7,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:00:37.658710-05:00,2,True,2019-12-02 08:58:37.557474-05:00,True
204,651387,34351205961,CVL2,YUS,0.724808,South,117,Arriving,6,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:05:20.919804080-05:00,2,True,2019-12-02 09:00:37.658710-05:00,True
210,660670,34351254953,GCN2,YUS,0.000000,South,117,AtStation,5,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:06:37.733512-05:00,2,True,2019-12-02 09:05:20.919804080-05:00,True
213,708738,34351278321,LWW2,YUS,0.954137,South,117,Arriving,4,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:08:34.837185480-05:00,2,True,2019-12-02 09:06:37.733512-05:00,NaN
221,647986,34351351205,YKD2,YUS,0.000000,South,117,AtStation,3,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:10:37.470245-05:00,2,True,2019-12-02 09:08:37.715613-05:00,True
223,675814,34351375664,WIL2,YUS,0.914541,South,117,Arriving,2,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:12:32.150665020-05:00,2,True,2019-12-02 09:10:37.470245-05:00,NaN
230,726969,34351472882,SHW2,YUS,0.000000,South,117,AtStation,1,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:15:37.608032-05:00,2,True,2019-12-02 09:12:37.695017-05:00,True
233,731903,34351499245,YUN2,YUS,0.645635,South,117,Arriving,77,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:17:16.231314740-05:00,2,True,2019-12-02 09:15:37.608032-05:00,NaN
231,727001,34351474203,DNP2,YUS,3.089306,South,117,Arriving,75,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:18:42.987971340-05:00,2,True,2019-12-02 09:17:37.649417-05:00,True
243,703551,34351550905,PVL2,YUS,0.357928,South,117,Arriving,78,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:18:59.131839340-05:00,2,True,2019-12-02 09:18:42.987971340-05:00,NaN
251,686764,34351602790,HWY2,YUS,0.687362,South,117,Arriving,79,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:21:19.193476840-05:00,2,True,2019-12-02 09:19:37.608962-05:00,True
232,727002,34351474427,FIW2,YUS,6.791902,South,117,Arriving,76,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:22:25.144163800-05:00,2,True,2019-12-02 09:21:19.193476840-05:00,True
257,658156,34351654478,VMC2,YUS,0.961779,South,117,Arriving,80,1,...,2019-12-02,9,0,AM,2,2019-12-02 09:23:35.521338120-05:00,2,True,2019-12-02 09:22:25.144163800-05:00,True
256,658156,34351654481,VMC1,YUS,0.961779,South,117,Arriving,80,1,...,2019-12-02,9,0,AM,1,2019-12-02 09:23:35.521338120-05:00,2,True,2019-12-02 09:23:35.521338120-05:00,True